import type { Insight } from "@/lib/cms";

/** French editions of the launch articles. Figures are carried across unchanged. */
export const insightsFr: Record<string, Partial<Insight>> = {
  "cost-of-living-mauritius-family": {
    title: "Ce que coûte la vie à Maurice : un budget réaliste pour une famille qui s'installe",
    summary:
      "Maurice n'est pas l'île bon marché que laissent entendre les brochures. Où va l'argent pour une famille qui arrive en 2026, avec les fourchettes qui comptent et les choix qui les font varier.",
    body: `
<p>L'idée reçue que nous corrigeons le plus souvent est que Maurice serait peu coûteuse. Pour une famille qui reproduit un mode de vie européen ou sud-africain, avec une maison sur la côte, des produits importés, une école internationale et une médecine privée, elle ne l'est pas. Les chiffres ci-dessous sont des fourchettes indicatives de 2026, destinées à dimensionner la décision, non à remplacer un budget en bonne et due forme. Ils varient avec le taux de change, la zone et les choix de la famille.</p>
<p><strong>Le logement.</strong> Le loyer est le poste le plus lourd et le plus variable. Un appartement moderne de deux chambres dans le nord, autour de Grand Baie, se situe entre 35 000 et 70 000 MUR par mois. Une maison familiale de trois chambres ou plus avec piscine, au nord ou à l'ouest, va d'environ 2 000 à 5 000 USD par mois, et les grandes villas des domaines dépassent largement ce niveau. À dix minutes de la côte, dans les terres, à Pamplemousses ou Triolet, le même budget offre nettement plus. Les locations sont presque toujours meublées, et une caution d'un à deux mois plus des honoraires d'agence se règlent avant l'arrivée.</p>
<p><strong>La scolarité.</strong> Le deuxième poste pour une famille avec enfants, et celui qui surprend le plus souvent. Les frais annuels des écoles internationales anglophones vont d'environ 180 000 MUR dans les petites classes à plus de 600 000 MUR en fin de secondaire, selon l'établissement. Une famille avec deux enfants au secondaire doit prévoir de 700 000 à 1 200 000 MUR par an de frais de scolarité seuls, avant les droits d'inscription, le bus scolaire et les extras. Une note distincte traite du choix de l'école.</p>
<p><strong>La santé.</strong> Les hôpitaux publics sont gratuits pour les résidents, mais la plupart des familles recourent aux cliniques privées et paient à l'acte. Une consultation chez un généraliste privé se situe entre 1 000 et 3 000 MUR. C'est l'assurance qui porte le coût réel : un contrat local de base à partir d'environ 2 000 à 4 000 MUR par mois et par personne, et un contrat international avec évacuation à partir d'environ 200 à 500 USD par mois. L'élément d'évacuation est celui sur lequel il ne faut pas économiser.</p>
<p><strong>Courses et charges.</strong> Les produits locaux, le poisson et le riz sont bon marché ; les produits importés supportent des droits et coûtent nettement plus qu'au pays. Une personne seule qui cuisine chez elle dépense environ 10 000 à 15 000 MUR par mois d'alimentation ; une famille deux à trois fois plus, davantage si le chariot est plein de marques importées. Électricité, eau et internet représentent quelques milliers de roupies par mois pour un foyer, en forte hausse l'été si la climatisation tourne toute la nuit.</p>
<p><strong>Les déplacements.</strong> La voiture est indispensable hors des villes, et les voitures coûtent cher en raison des droits d'importation. Prévoyez cet achat, et le carburant, dès le départ. Les transports publics existent, mais ce n'est pas ainsi qu'une famille qui s'installe conduira les enfants à l'école.</p>
<p><strong>Ce que l'on obtient en échange.</strong> Une fiscalité personnelle plafonnée à 20 %, à laquelle s'ajoute une Fair Share Contribution de 15 % au-delà de 12 millions MUR en vigueur jusqu'au 30 juin 2028, une base de remise pour les revenus étrangers, pas d'impôt sur les plus-values, pas d'impôt sur la fortune, pas de droits de succession. La sécurité. Une aide à domicile à des salaires bas selon les standards européens. Un hiver qui n'existe pas. La plupart des familles qui font honnêtement leurs comptes trouvent un total comparable à celui d'une ville européenne de taille moyenne, et constatent qu'elles paient pour la vie qu'elles mènent, non pour une remise.</p>
`,
    faqs: [
      { q: "Vaut-il mieux acheter que louer ?", a: "Sur un horizon long, souvent, et une acquisition à partir de 375 000 USD dans un programme agréé ouvre un permis de résidence. Mais nous conseillons à chaque famille de louer la première année. L'endroit où l'on croit vouloir vivre et celui où l'on veut vraiment vivre sont fréquemment différents." },
      { q: "Quel budget prévoir pour le déménagement lui-même ?", a: "Deux voyages de reconnaissance, le transport ou le rachat du mobilier, les cautions du logement et de l'école, la voiture, et les honoraires professionnels pour le permis et la société. Ensemble, ces postes dépassent généralement ce que les familles anticipent, et ils tombent dans les trois premiers mois." },
      { q: "Les coûts diffèrent-ils beaucoup entre le nord, l'ouest et le centre ?", a: "Oui. La côte nord est la plus chère pour le logement, l'ouest suit de près, et le centre autour de Moka est nettement moins cher à maison équivalente, tout en étant plus proche des écoles et des bureaux. Les villages de l'intérieur, à cinq ou dix minutes de la côte, sont moins chers encore." },
    ],
  },

  "international-schools-mauritius-choosing": {
    title: "Choisir une école à Maurice : programmes, zones, frais et calendrier",
    summary:
      "C'est l'école qui décide où vous habitez, et non l'inverse. Les options anglaises, françaises et IB de l'île, leur coût, et pourquoi la demande d'inscription doit précéder celle du permis.",
    body: `
<p>Nous disons la même chose à chaque famille dès le premier rendez-vous : choisissez l'école avant la maison. L'île est petite, la circulation ne l'est pas, et le trajet quotidien depuis la mauvaise côte vers la bonne école est la raison la plus fréquente pour laquelle des familles déménagent dans l'année qui suit leur arrivée.</p>
<p><strong>Trois systèmes.</strong> Les écoles anglophones suivent le programme britannique jusqu'aux Cambridge IGCSE et A-Levels, plusieurs proposant aussi le Baccalauréat International ; les écoles françaises suivent le programme national français jusqu'au baccalauréat, homologuées par le ministère français, et l'une d'elles propose le diplôme de l'IB dans les dernières années ; enfin les écoles publiques mauriciennes, gratuites et bilingues, mais rarement choisies par les familles qui s'installent. Pour une entrée à l'université britannique ou sud-africaine, les A-Levels et l'IB sont également acceptés. Pour une famille susceptible de repartir, le programme dans lequel elle se trouve déjà est généralement celui qu'il faut conserver.</p>
<p><strong>Où sont les écoles.</strong> Le nord abrite la plus grande et la plus établie des écoles anglophones, à Mapou, qui accueille les enfants de 18 mois à 18 ans, ainsi qu'une école primaire réputée dans le même village et une école française. L'ouest dispose d'un secondaire anglophone près de Flic en Flac et d'une offre primaire et secondaire en développement autour de Tamarin. Le plateau central, autour de Moka, réunit le second des deux grands établissements secondaires anglophones, une autre école IB, ainsi que le principal lycée et la principale école français. L'est et le sud comptent beaucoup moins d'options, et les familles qui y vivent acceptent de longs trajets.</p>
<p><strong>Les frais.</strong> Les écoles anglophones facturent par niveau, et le saut à l'entrée au secondaire est marqué. Les frais publiés pour 2025-26 dans le plus grand établissement vont d'environ 161 700 MUR par an dans les petites classes à 608 300 MUR dans les dernières années. Le secondaire de Moka facture environ 32 000 à 35 000 MUR par mois sur onze mois. Des droits d'inscription de 10 000 à 30 000 MUR et un bus scolaire de 18 000 à 40 000 MUR par an s'y ajoutent, et des réductions fratrie de 7,5 % à 15 % sont courantes. Les écoles françaises sont moins onéreuses. Les frais sont révisés chaque année : confirmez les montants en vigueur auprès de l'école avant d'établir un budget.</p>
<p><strong>Le calendrier.</strong> Les bonnes écoles ont des listes d'attente dans les niveaux où les familles arrivent le plus souvent, en particulier les premières années de primaire et la première année de secondaire. Six à douze mois d'anticipation sont la norme, davantage est plus sûr. Autrement dit, la demande d'inscription précède la demande de permis, et l'acompte d'inscription est souvent la première dépense du déménagement.</p>
<p><strong>Ce que nous faisons.</strong> Présenter à la famille les deux ou trois écoles qui correspondent à l'âge des enfants et au programme suivi, organiser les visites lors d'un voyage de reconnaissance, gérer la correspondance d'admission, et aligner la date de l'offre sur le calendrier du permis afin que la place soit tenue jusqu'à ce que la famille puisse la prendre.</p>
`,
    faqs: [
      { q: "Nos enfants doivent-ils parler français ?", a: "Pas pour les écoles anglophones, qui enseignent en anglais et proposent le français comme matière. Les écoles du programme français exigent le français dès un stade précoce. La plupart des enfants acquièrent rapidement un français et un créole de conversation, quel que soit le cas." },
      { q: "Pouvons-nous visiter avant de décider ?", a: "Oui, et vous devriez. Un voyage de reconnaissance en période scolaire, avec visites d'écoles et trajet domicile-école effectué à l'heure de pointe, est le meilleur investissement d'une famille avant de s'installer." },
      { q: "L'internat existe-t-il ?", a: "De façon limitée. Maurice est une île d'externats. Les familles de la côte est ou sud recourent parfois à des formules d'internat en semaine, mais la plupart choisissent d'habiter près de l'école." },
    ],
  },

  "healthcare-mauritius-what-to-arrange": {
    title: "La santé à Maurice : ce qui existe, ce qui n'existe pas, et ce qu'il faut prévoir avant d'arriver",
    summary:
      "De bonnes cliniques privées, un système public gratuit que la plupart des résidents évitent, et un petit nombre de pathologies traitées à l'étranger. Pourquoi la clause d'évacuation est la seule qui compte vraiment.",
    body: `
<p>Maurice a un système à deux étages. Les hôpitaux publics sont gratuits pour les résidents, assurent l'essentiel des soins de l'île et sont saturés. Les cliniques privées sont l'endroit où vont les familles qui s'installent, et elles sont bonnes : des médecins formés en France, au Royaume-Uni, en Inde et en Afrique du Sud, un matériel moderne, des attentes courtes, et l'anglais comme le français parlés partout.</p>
<p><strong>Les cliniques à connaître.</strong> Les deux hôpitaux privés de plein exercice sont au centre de l'île : le Wellkin Hospital du groupe C-Care à Moka, le plus grand et le plus moderne, avec une unité de soins intensifs et des urgences ouvertes 24 heures sur 24, et la Clinique Darné à Floréal, établie de longue date, avec maternité et soins intensifs. Il existe des cliniques privées au nord à Grand Baie et le long de la route côtière, ainsi qu'un réseau de laboratoires agréés pour les examens exigés par le permis. Depuis Tamarin ou Grand Baie, les hôpitaux de Moka sont à environ vingt à trente minutes hors circulation.</p>
<p><strong>Ce qui se traite à l'étranger.</strong> L'île est petite et certaines spécialités n'ont pas le volume nécessaire pour exister ici. L'oncologie avancée, la chirurgie cardiaque complexe et la neurochirurgie lourde sont couramment orientées vers l'Afrique du Sud, La Réunion ou la France. Ce n'est pas une défaillance du système, c'est la conséquence d'une population de 1,3 million d'habitants. Mais cela a une implication directe pour une famille qui s'installe : l'assurance santé doit inclure l'évacuation sanitaire et les soins à l'étranger, et c'est la clause à lire avant de signer.</p>
<p><strong>L'assurance.</strong> Deux voies. Les assureurs locaux proposent des contrats à partir d'environ 2 000 à 4 000 MUR par mois et par personne pour les consultations privées, l'hospitalisation et les médicaments à Maurice, généralement sans évacuation. Les assureurs internationaux proposent des contrats à partir d'environ 200 à 500 USD par mois et par personne, avec une couverture mondiale et l'évacuation incluse. Beaucoup de familles combinent un contrat local pour le quotidien et une couverture internationale pour les cas graves. Vérifiez le traitement des antécédents médicaux, la couverture des personnes à charge sur un contrat d'employeur, et l'existence d'un accord de tiers payant entre la clinique que vous utiliseriez et l'assureur.</p>
<p><strong>La santé au quotidien.</strong> Les pharmacies sont bien approvisionnées et de nombreux médicaments sont disponibles sans ordonnance à des prix raisonnables ; la disponibilité de traitements de marque précis doit être vérifiée avant le déménagement. L'eau du robinet est traitée, mais la plupart des foyers la filtrent. La dengue et le chikungunya circulent pendant les mois d'été et le moustique est le seul animal à prendre au sérieux ; le paludisme est pratiquement absent. La saison cyclonique court de novembre à avril, la période formelle d'alerte s'étendant jusqu'à la mi-mai, et les cliniques restent ouvertes pendant toute cette période.</p>
<p><strong>Ce que nous organisons.</strong> L'examen médical exigé par le permis, dans une clinique agréée, calé sur la demande. La présentation d'un généraliste, d'un pédiatre et d'un dentiste près du lieu de vie de la famille. Et la conversation sur l'assurance avant l'arrivée plutôt qu'après, parce que la clause d'évacuation est plus facile à régler sur le papier qu'en pleine urgence.</p>
`,
    faqs: [
      { q: "Le système public est-il utilisable en urgence ?", a: "Pour un traumatisme aigu, oui : les services publics d'urgence stabilisent bien. Le schéma habituel est une stabilisation à l'hôpital le plus proche puis un transfert vers une clinique privée pour la suite des soins, raison pour laquelle le numéro de l'assureur doit figurer dans votre téléphone." },
      { q: "Pouvons-nous conserver notre contrat international existant ?", a: "Souvent, s'il couvre Maurice et inclut l'évacuation. Vérifiez si l'assureur considère Maurice comme votre pays de résidence plutôt que comme une destination de voyage, car cela change les conditions." },
      { q: "Les examens médicaux du permis sont-ils exigeants ?", a: "Non. Une série d'analyses sanguines standard, une radiographie du thorax et un certificat d'un praticien agréé à Maurice. Trois des examens doivent être faits sur place ; les autres peuvent l'être avant le voyage. Nous prenons les rendez-vous." },
    ],
  },

  "where-to-live-mauritius-north-west-centre": {
    title: "Où vivre à Maurice : nord, ouest ou centre",
    summary:
      "Trois régions accueillent la quasi-totalité des familles qui s'installent. À quoi ressemble la vie dans chacune, qui les choisit, et le trajet quotidien qui tranche entre elles.",
    body: `
<p>Maurice fait 65 kilomètres du nord au sud, et pourtant l'endroit où une famille vit façonne son année davantage que dans la plupart des pays plus vastes. La raison tient au réseau routier : une seule autoroute traversant Port-Louis, et des routes côtières qui saturent aux heures d'école. Les trois régions ci-dessous accueillent presque toutes les familles que nous installons, et le choix entre elles se décide généralement par l'école et le bureau plutôt que par la plage.</p>
<p><strong>Le nord.</strong> Grand Baie et la côte alentour, de Trou aux Biches à Pereybère et Cap Malheureux, concentre la plus forte population de résidents étrangers de l'île. Les raisons sont pratiques : la plus grande école internationale à Mapou, une école française, deux cliniques privées, la marina, des supermarchés proposant des gammes importées, restaurants et commerces sur une même artère, et une forte densité de programmes agréés, dont le Mont Choisy Golf &amp; Beach Estate est le plus connu. Le prix à payer est celui du logement, le plus élevé de l'île, et la circulation, qui a crû avec la population. Les familles qui veulent tout à pied, et qui travaillent chez elles ou dans le nord, choisissent cette zone. À dix minutes dans les terres, Pamplemousses et Triolet offrent les mêmes écoles à des loyers inférieurs, et les domaines sécurisés autour de Piton, parmi lesquels le Domaine de Bon Espoir, conviennent aux familles qui veulent un cadre plus vert avec l'autoroute à proximité.</p>
<p><strong>L'ouest.</strong> Tamarin, Rivière Noire et Flic en Flac, la montagne derrière et le lagon devant. Plus sec et plus chaud que le nord et à l'abri des alizés, même si la construction s'est accélérée le long de cette côte : la région est plus détendue par son caractère qu'uniformément calme. La Balise Marina, à Rivière Noire, est la seule véritable adresse de marina de l'île, où l'amarrage se trouve au bout du jardin. avec le surf, le kitesurf et la randonnée de l'île à la porte, et une communauté soudée de résidents de longue date. On y trouve un secondaire anglophone près de Flic en Flac et une offre scolaire en développement à Tamarin, et Port-Louis est plus proche que depuis Grand Baie. Les étés sont chauds, et la route vers les écoles de Mapou prend vingt-cinq minutes un bon jour. Les familles qui veulent le grand air et un rythme plus lent choisissent l'ouest ; les retraités aussi.</p>
<p><strong>Le centre.</strong> Moka et le plateau alentour, avec le quartier de bureaux d'Ébène, les deux principaux hôpitaux privés, le second grand secondaire anglophone, une école IB et le lycée français, tous à quelques minutes les uns des autres. Les projets Smart City en ont fait un choix résidentiel plutôt qu'un lieu où l'on se rend pour travailler. Il y fait plus frais et plus humide que sur la côte, et la mer est à vingt ou trente minutes dans toutes les directions. Les loyers y sont nettement inférieurs à ceux de la côte à maison équivalente. Les familles avec des enfants au secondaire et un parent travaillant à Ébène ou à Port-Louis le choisissent de plus en plus, et le trajet en est la raison.</p>
<p><strong>L'est et le sud.</strong> Beaux, moins urbanisés et moins chers, avec une poignée de grands domaines hôteliers. Peu d'écoles et de longs trajets vers celles qui existent. Choisis par les familles sans enfants scolarisés et par les acquéreurs d'un domaine précis.</p>
<p>Si nous citons ces domaines, c'est parce que les clients nous en parlent par leur nom, non parce que nous agissons pour quiconque y vend. Nous agissons pour l'acquéreur seul, ne percevons aucune commission des promoteurs ni des vendeurs, et tout avis que nous donnons sur un programme l'est en ne considérant que la position de l'acquéreur.</p>
<p><strong>Comment décider.</strong> Trouvez l'école. Trouvez le bureau, s'il y en a un. Parcourez le trajet entre eux et les maisons envisagées à huit heures du matin un jour de classe. Puis choisissez. Nous organisons les voyages de reconnaissance autour de cet exercice précis, avec des visites dans deux régions et le trajet scolaire effectué à l'heure qui compte.</p>
`,
    faqs: [
      { q: "Grand Baie est-elle trop chère ?", a: "Pour ce que l'on obtient dans certains secteurs, oui, et les résidents de longue date le diront. On paie la commodité. Si cette commodité compte pour votre famille, cela les vaut ; sinon, regardez vers l'intérieur ou vers l'ouest." },
      { q: "Quelle région a le meilleur climat ?", a: "L'ouest, plus sec et plus abrité. Le nord est chaud et plus venteux. Le centre est plus frais et plus humide, ce que certaines familles préfèrent l'été et d'autres non." },
      { q: "Les domaines sécurisés en valent-ils la peine ?", a: "Pour la sécurité, la vie de quartier et les services, souvent oui, et pour un non-citoyen qui achète, ils sont fréquemment la seule option. En location, une maison de village peut offrir plus d'espace pour le même prix, au prix d'un peu de commodité." },
    ],
  },

  "bringing-pets-to-mauritius": {
    title: "Emmener un chien ou un chat à Maurice",
    summary:
      "Maurice est indemne de rage et protège soigneusement ce statut. Ce qu'implique la procédure d'importation, sa durée, et pourquoi elle doit commencer avant la demande de permis.",
    body: `
<p>Maurice est indemne de rage et entend le rester, ce qui fait de l'arrivée d'un animal l'un des postes les plus longs d'une installation. C'est tout à fait faisable, et de nombreuses familles le font, mais le calendrier est dicté par des analyses sanguines et des délais d'attente plutôt que par des formalités, et une famille qui s'y prend tard peut voir le chien arriver des mois après elle.</p>
<p><strong>Qui décide.</strong> L'importation d'animaux vivants est réglementée par la Livestock and Veterinary Division du ministère de l'Agro-Industrie, qui délivre un permis d'importation pour chaque animal et publie les directives en vigueur pour les chiens et les chats. Seuls les animaux provenant de pays classés par le ministère comme indemnes de rage ou à rage maîtrisée sont admis ; un animal venant d'un pays à haut risque ne le sera pas.</p>
<p><strong>Ce qu'il faut pour l'animal.</strong> Une puce électronique. Une vaccination antirabique à jour, administrée après la pose de la puce et dans la fenêtre de validité fixée par les directives. Un titrage des anticorps antirabiques dans un laboratoire agréé, montrant un résultat d'au moins 0,5 UI/ml, réalisé dans une fenêtre définie avant le voyage ; les directives l'encadrent actuellement entre trois mois au minimum et douze mois au maximum avant l'expédition, et certains pays d'origine, dont l'Afrique du Sud, se voient demander deux titrages à trois mois d'intervalle. Les vaccinations habituelles contre la maladie de Carré, la parvovirose et leurs équivalents félins. Un traitement antiparasitaire. La stérilisation, dans la plupart des cas. Un certificat sanitaire délivré par un vétérinaire officiel du pays de départ peu avant le vol.</p>
<p><strong>À l'arrivée.</strong> Le permis d'importation doit être obtenu avant le voyage de l'animal, l'agent vétérinaire informé du vol, et l'animal est placé en quarantaine à la station gouvernementale. La durée dépend du pays d'origine et de l'historique de l'animal ; les sources évoquent de cinq jours à un mois : prévoyez la durée la plus longue et réjouissez-vous si elle est plus courte. Les propriétaires peuvent rendre visite et doivent fournir la nourriture et le couchage.</p>
<p><strong>Le calendrier.</strong> En raison du titrage et du délai qui doit s'écouler ensuite, le délai réaliste, en partant de zéro, est de quatre à six mois, davantage pour un animal jamais vacciné. Les familles qui viennent en reconnaissance au printemps et déménagent à l'automne devraient ouvrir le dossier de l'animal avant ce voyage.</p>
<p><strong>Les vols.</strong> Les liaisons directes depuis Johannesburg, Paris, Londres et Dubaï évitent les problèmes de transit qui compliquent le transport animalier. Les chiens dépassant la taille cabine voyagent en soute pressurisée, et les sociétés spécialisées d'Afrique du Sud et d'Europe s'occupent de la caisse, de la compagnie aérienne et du visa vétérinaire. Nous vous en présentons une dans le cadre de l'installation.</p>
<p>Les exigences ci-dessus sont celles publiées à la date de rédaction. Le ministère les révise, et nous confirmons la directive en vigueur et le classement du pays d'origine au moment où une famille nous mandate.</p>
`,
    faqs: [
      { q: "Pouvons-nous emmener un chiot ou un chaton ?", a: "Pas sous couvert des vaccinations de la mère. La première vaccination antirabique se fait à douze semaines et la procédure d'exportation part de là : un jeune animal aura donc plusieurs mois avant de pouvoir voyager." },
      { q: "Certaines races sont-elles interdites ?", a: "Maurice restreint certaines races de chiens. Vérifiez la liste en vigueur auprès de la Livestock and Veterinary Division avant de supposer qu'un chien donné pourra venir." },
      { q: "L'animal a-t-il une incidence sur notre propre permis ?", a: "Non. Les deux procédures sont distinctes, mais elles doivent être planifiées ensemble, car le calendrier de l'animal est souvent le plus long." },
    ],
  },

  "buying-off-plan-mauritius-vefa-checklist": {
    title: "Acheter sur plan à Maurice : ce qu'il faut vérifier avant de signer une VEFA",
    summary:
      "La plupart des logements neufs vendus à des acquéreurs étrangers à Maurice le sont avant d'être construits. La protection est réelle, mais elle se joue à la signature. Cinq points à examiner d'abord.",
    body: `
<p>La vente en l'état futur d'achèvement, la VEFA, est le mode par lequel se transmet la majorité des biens des programmes agréés à Maurice. L'acquéreur signe un acte devant notaire alors que le bâtiment n'est qu'un plan, paie par tranches à mesure qu'il s'élève, et s'appuie sur une garantie bancaire pour le voir achevé si le promoteur ne le peut pas. Le système fonctionne. Mais la protection de l'acquéreur se fixe le jour de la signature, et nous avons agi pour assez d'acquéreurs dans des programmes à l'arrêt pour savoir que l'écart entre une position récupérable et une position difficile se trouve presque toujours dans l'acte.</p>
<p><strong>Qui a émis la garantie d'achèvement, et que couvre-t-elle.</strong> La garantie financière d'achèvement est le cœur d'une VEFA. Demandez la garantie elle-même, non une référence à celle-ci. Identifiez la banque ou l'assureur émetteur. Lisez ce qui la déclenche, ce qu'elle paie, et si elle couvre l'achèvement du bâtiment ou seulement le remboursement de ce que vous avez versé. Une garantie émise par un établissement dont vous n'avez jamais entendu parler, ou plafonnée en dessous du prix du contrat, est un signal d'alerte.</p>
<p><strong>L'échéancier suit-il le chantier.</strong> Les tranches doivent être liées à des jalons physiques qu'un tiers peut vérifier : fondations, structure, toiture, achèvement, livraison. Un échéancier concentré sur la signature, ou qui appelle un paiement au « commencement des travaux » sans le définir, déplace le risque vers l'acquéreur. Comparez l'échéancier de l'acte avec celui de la brochure. Ils ne coïncident pas toujours.</p>
<p><strong>Ce que le promoteur a déjà achevé.</strong> Un promoteur ayant trois programmes livrés sur l'île n'est pas la même proposition qu'un promoteur dont c'est le premier projet, si belles que soient les images de synthèse. Demandez quels programmes il a livrés, quand, et dans les délais ou non. Allez en visiter un. Parlez à un propriétaire sur place. Le notaire ne le fera pas pour vous.</p>
<p><strong>La date de livraison et ce qui se passe en cas de retard.</strong> L'acte indiquera une date de livraison et, généralement, une liste d'événements excusant le retard. Lisez cette liste. Si elle excuse à peu près tout, la date ne signifie pas grand-chose. Cherchez une pénalité journalière ou mensuelle de retard et vérifiez si elle est plafonnée. Une clause pénale sans plafond assortie d'une liste d'excuses courte vous indique que le promoteur compte bien finir.</p>
<p><strong>La structure par laquelle vous achetez.</strong> Si le bien doit être détenu par une société mauricienne, et la société par un trust, cette structure doit exister avant l'acte et être acceptable pour la banque émettrice de la garantie, pour le notaire et pour l'Economic Development Board. La mettre en place après la réservation et avant l'acte est courant. La mettre en place après l'acte constitue une seconde opération.</p>
<p>Le notaire agit pour l'opération, non pour l'acquéreur. Sa mission est un acte valable, régulièrement enregistré. Savoir si cet acte constitue une bonne affaire pour vous n'est pas sa question. C'est la nôtre, et elle se pose au mieux avant le versement de l'acompte de réservation plutôt qu'après.</p>
`,
    faqs: [
      { q: "Puis-je négocier l'échéancier de paiement ?", a: "Parfois, en particulier tôt dans un programme, lorsque le promoteur cherche des signatures. Le plus souvent l'échéancier est figé, mais l'acte peut être amélioré sur les conditions de livraison, les pénalités et la rédaction de la garantie. Demandez avant de signer ; rien ne change ensuite." },
      { q: "Que se passe-t-il si le promoteur cesse de construire ?", a: "La garantie d'achèvement est appelée et le garant finance l'achèvement ou rembourse les acquéreurs, selon ses termes. La procédure passe par le notaire et le garant et peut prendre du temps. Les acquéreurs qui connaissent les termes de la garantie avant de signer sont en bien meilleure position que ceux qui les découvrent à l'arrêt du chantier." },
      { q: "Le permis de résidence dépend-il de l'achèvement ?", a: "Le permis est demandé une fois l'acte signé et l'acquisition enregistrée par l'EDB : il n'attend donc pas le bâtiment. Si le programme échoue et que l'acquisition est dénouée, le permis tombe avec elle." },
    ],
  },

  "retiring-to-mauritius-from-germany-austria-switzerland": {
    title: "Prendre sa retraite à Maurice depuis l'Allemagne, l'Autriche ou la Suisse : le permis, et les questions fiscales à poser",
    summary:
      "Le permis Retired Non-Citizen est simple. L'articulation entre la résidence mauricienne et une pension allemande, autrichienne ou suisse ne l'est pas. Ce qu'il faut régler avant de partir.",
    body: `
<p>Chaque mois, un couple de Munich, de Vienne ou de Zurich nous écrit après avoir découvert Maurice lors de vacances d'hiver et veut savoir combien il serait difficile d'y rester. Le permis est la partie facile. C'est la situation fiscale qui emporte réellement la décision, et c'est celle que la plupart des sites passent sous silence ou traitent mal.</p>
<p><strong>Le permis.</strong> Toute personne de 50 ans ou plus peut demander un permis de résidence Retired Non-Citizen. Il court dix ans, n'exige aucun achat immobilier, et repose sur le transfert de 24 000 USD par an depuis l'étranger vers un compte bancaire mauricien, soit 2 000 USD par mois. Un conjoint de moins de 50 ans rejoint le permis comme personne à charge. L'emploi n'est pas autorisé sous ce permis, mais l'investissement en qualité d'actionnaire l'est. Après cinq ans, avec des transferts cumulés de 200 000 USD, le titulaire peut demander un permis de résidence permanente de vingt ans. Voilà tout le cadre.</p>
<p><strong>La résidence fiscale.</strong> Passez 183 jours ou plus à Maurice au cours d'une année fiscale et vous y êtes résident fiscal. Maurice impose les revenus de source étrangère sur une base de remise et dispose de conventions de non-double imposition en vigueur avec l'Allemagne et avec d'autres juridictions européennes. Savoir s'il en existe une avec votre pays, et ce que cette convention dit des pensions, est la première chose à établir.</p>
<p><strong>Les questions à poser à un conseil fiscal avant de décider.</strong> Nous ne sommes pas conseils fiscaux et ne rendons pas d'avis fiscal. Nous savons en revanche quelles questions produisent une réponse utile.</p>
<ul>
<li>Lesquels de mes flux de revenus sont imposés dans le pays où ils naissent au sens de la convention, et lesquels me suivent à Maurice ? Pensions publiques, retraites professionnelles, rentes privées et revenus de placements sont souvent traités différemment les uns des autres.</li>
<li>Que mon pays d'origine exige-t-il pour admettre que je suis parti ? Radiation, fin d'un foyer d'habitation habituel, nombre de jours que je peux encore y passer. L'Allemagne et l'Autriche en particulier regardent les liens, et pas seulement les jours.</li>
<li>Si je conserve un appartement au pays, cela m'y maintient-il résident fiscal ?</li>
<li>Comment la base de remise mauricienne s'articule-t-elle avec les transferts exigés par le permis ? L'argent apporté pour satisfaire la condition du permis est, par définition, rapatrié.</li>
<li>Existe-t-il une exit tax, une imposition différée ou une reprise sur un produit de retraite ou de placement que je détiens si je deviens non-résident ?</li>
<li>Mon assureur santé continuera-t-il à me couvrir à l'étranger, et combien coûte une couverture privée mauricienne à mon âge ?</li>
</ul>
<p>Les réponses varient suffisamment entre les trois pays, et d'une personne à l'autre, pour qu'aucun site ne puisse les donner. Ce dont un bon conseil a besoin de votre part, c'est d'une liste claire de vos sources de revenus, des actifs que vous conserveriez au pays, et des jours que vous comptez passer où. Ce que nous faisons, c'est présenter le conseil, mettre ces éléments devant lui, et retenir la demande de permis jusqu'à ce que les réponses soient là.</p>
<p>La plupart des couples qui posent ces questions partent quand même. Ils partent avec un plan plutôt qu'avec une supposition, et c'est la seule différence qui compte.</p>
`,
    faqs: [
      { q: "Dois-je vendre ma maison en Europe ?", a: "Pas pour le permis. Savoir si la conserver affecte votre résidence fiscale au pays est une question pour votre conseil sur place, et la réponse diffère entre l'Allemagne, l'Autriche et la Suisse." },
      { q: "Puis-je emmener ma voiture, mes meubles et mes effets personnels ?", a: "Oui, et un titulaire de permis de résidence peut importer ses effets domestiques en franchise de droits, sous conditions. Le véhicule est une question distincte et n'en vaut souvent pas la peine. Nous traitons ce volet dans le cadre de l'installation." },
      { q: "Pourrai-je ouvrir un compte bancaire à 65 ans sans revenu mauricien ?", a: "Oui. Les banques connaissent bien le permis pour retraités. Ce qu'elles examineront de près est l'origine de votre patrimoine : le dossier que nous préparons pour la banque est donc plus détaillé que celui du permis." },
    ],
  },

  "south-africans-relocating-to-mauritius-permit-and-cost": {
    title: "Les Sud-Africains qui s'installent à Maurice : quel permis, et ce que coûte la première année",
    summary:
      "Les trois voies que retiennent le plus souvent les familles sud-africaines, et un compte rendu honnête de la destination de l'argent au cours des douze premiers mois.",
    body: `
<p>Les Sud-Africains constituent le premier groupe de résidents étrangers arrivant à Maurice, et les raisons sont connues : quatre heures de vol, le même fuseau horaire, des écoles anglophones, une monnaie stable et un État qui fonctionne. La question qu'on nous pose le plus souvent n'est pas s'il faut venir, mais par quelle porte et à quel prix. Voici la version courte.</p>
<p><strong>Trois voies.</strong> L'entrepreneur qui dirigera une activité ici prend l'Occupation Permit Investisseur : 100 000 USD dans une société mauricienne, conditions de chiffre d'affaires à partir de la troisième année, dix ans de validité. Le professionnel ou consultant qui travaille seul prend le permis Self-Employed à 50 000 USD. Toute personne de plus de 50 ans vivant de revenus sud-africains prend le permis Retired Non-Citizen sur des transferts de 24 000 USD par an. Une quatrième porte, l'achat d'un logement dans un programme agréé à partir de 375 000 USD, ouvre un permis de résidence tant que le bien est détenu, et convient aux familles qui comptaient acheter de toute façon. La plupart des familles sud-africaines empruntent l'une des trois premières et louent la première année.</p>
<p><strong>Où va l'argent la première année.</strong> Abstraction faite de l'investissement du permis lui-même, qui est un fonds de roulement ou de l'argent de vie plutôt qu'un honoraire, les coûts se répartissent en six groupes, à peu près par ordre décroissant.</p>
<ul>
<li>Le logement. Le loyer d'une maison de trois chambres avec piscine au nord ou à l'ouest est le poste le plus lourd. Cautions, honoraires d'agence et premiers mois de loyer se règlent avant l'arrivée.</li>
<li>La scolarité. Les écoles internationales facturent en roupies et les frais sont significatifs, mais bien inférieurs à leur équivalent dans le Golfe ou à Singapour. Les places se remplissent tôt et les acomptes d'inscription sont dus à l'acceptation.</li>
<li>La constitution. Immatriculation, siège social et company secretary, un administrateur résident si nécessaire, et le compte bancaire. Pour la voie Investisseur, c'est un forfait ; pour la voie retraite, c'est minimal.</li>
<li>Le permis lui-même. Les taxes publiques sont modestes. Nos honoraires de préparation et de suivi du dossier figurent dans la proposition écrite avant tout commencement.</li>
<li>La couverture santé. Une assurance privée valable à Maurice et couvrant l'orientation vers l'Afrique du Sud n'est pas facultative et doit être souscrite avant l'arrivée.</li>
<li>Véhicule et maison. Une voiture, l'immatriculation et l'assurance ; les branchements et abonnements ; le personnel de maison si souhaité, à des salaires bas selon les standards sud-africains.</li>
</ul>
<p><strong>Le contrôle des changes.</strong> Sortir des capitaux d'Afrique du Sud relève des règles de la South African Reserve Bank et de vos allocations annuelles, et le calendrier des transferts doit être planifié en tenant compte de l'échéance du permis. Les permis Investisseur et Self-Employed exigent que l'investissement initial arrive dans les 60 jours suivant la délivrance, et un transfert retardé annule le permis. Nous ne conseillons pas sur le contrôle des changes sud-africain, mais nous séquençons le permis pour que l'argent soit prêt lorsque le compte à rebours commence.</p>
<p><strong>Ce que nous dirions à un ami.</strong> Louez avant d'acheter. Choisissez l'école avant la maison. Faites ouvrir le compte bancaire avant la délivrance du permis, non après. Prévoyez deux voyages avant le déménagement, un pour voir et un pour signer. Et choisissez la voie en fonction de ce à quoi ressembleront l'entreprise ou le foyer dans trois ans, non du plus petit chiffre de la page.</p>
`,
    faqs: [
      { q: "Puis-je conserver mon entreprise sud-africaine et la diriger depuis Maurice ?", a: "Oui, et beaucoup le font, via une société mauricienne qui contracte avec la société sud-africaine ou reprend l'activité export. La structure compte pour les deux systèmes fiscaux et doit être conçue avant la demande de permis plutôt qu'après." },
      { q: "Mon conjoint peut-il travailler ?", a: "Pas avec un permis de personne à charge. L'organisation habituelle est un permis Investisseur pour un conjoint et un permis Professionnel pour l'autre, employé par la même société mauricienne, ou un second Occupation Permit en son nom propre." },
      { q: "Combien de temps avant de pouvoir déménager ?", a: "De la première conversation à une famille installée dans une maison avec les enfants scolarisés, trois à six mois est réaliste, le compte bancaire et la place à l'école donnant le rythme plutôt que le permis." },
    ],
  },

  "occupation-permit-changes-2026-27-budget": {
    title: "Ce que le Budget 2026-27 a changé pour les Occupation Permits",
    summary:
      "Des seuils relevés pour les investisseurs, une catégorie professionnelle unique et des conditions de revenus resserrées pour les indépendants. Ce que cela signifie si vous préparez une installation cette année.",
    body: `
<p>Le Budget 2026-27 a apporté la révision la plus importante du cadre des Occupation Permits depuis plusieurs années, et l'Economic Development Board a désormais publié des directives révisées pour la mettre en œuvre. Quatre changements comptent pour qui prépare une installation.</p>
<p><strong>Le seuil Investisseur a doublé.</strong> L'investissement initial minimum est désormais de 100 000 USD, transférés depuis l'étranger sur le compte mauricien de la société dans les 60 jours suivant la délivrance du permis. Les conditions de chiffre d'affaires qui suivent sont également nouvelles : 5 millions MUR par an à partir de la troisième année d'enregistrement, portés à 8 millions MUR à partir de la cinquième année pour le renouvellement. Un investisseur dont le plan d'affaires ne peut raisonnablement atteindre ces montants devrait examiner sérieusement si la voie Investisseur est la bonne.</p>
<p><strong>Une seule catégorie professionnelle.</strong> Les anciens paliers ProPass et Expert Pass ont été fusionnés. Le salaire mensuel de base minimum est désormais de 50 000 MUR dans tous les secteurs. Les professionnels détenant déjà un permis sous l'ancien critère de 30 000 MUR restent éligibles à un renouvellement sur cette base, ce qui laisse du temps aux titulaires actuels.</p>
<p><strong>Les conditions de revenus des indépendants.</strong> L'investissement initial reste à 50 000 USD, mais les conditions de revenus sont désormais explicites : 2 millions MUR par an à partir de la troisième année, et 3 millions MUR à partir de la cinquième année pour le renouvellement. Trois lettres d'intention, dont deux de clients locaux, sont exigées au dépôt.</p>
<p><strong>Le Family Occupation Permit a disparu.</strong> La catégorie a été supprimée. Les familles passent désormais par le titulaire principal et des permis de personnes à charge, ce qui, pour la plupart, correspond à ce qu'elles faisaient déjà.</p>
<p>Rien de tout cela ne rend Maurice plus difficile d'accès pour ceux qu'elle souhaite accueillir. Cela rend le choix de la voie plus lourd de conséquences. L'écart entre Investisseur et Self-Employed, ou entre un Occupation Permit et la résidence par l'immobilier, se mesure désormais en argent réel et en obligations de chiffre d'affaires réelles, et mérite une heure de réflexion avant tout dépôt.</p>
`,
  },

  "investor-or-self-employed": {
    title: "Investisseur ou Self-Employed : choisir le bon Occupation Permit",
    summary:
      "Les deux voies destinées à ceux qui travailleront à leur compte à Maurice diffèrent par le capital, la structure et les obligations. Un guide bref pour savoir laquelle convient.",
    body: `
<p>La plupart de ceux qui gagneront leur vie à Maurice à leur compte arrivent avec l'un de deux permis en tête. Le choix entre eux tient moins à l'activité qu'à sa forme.</p>
<p><strong>Le capital.</strong> Le permis Self-Employed exige 50 000 USD transférés depuis l'étranger. Le permis Investisseur exige 100 000 USD, sur le compte d'une société. Pour beaucoup, cette différence tranche la question, et il n'y a rien à y redire.</p>
<p><strong>La structure.</strong> Un titulaire Self-Employed travaille en son nom propre ou via une société unipersonnelle, peut employer un salarié administratif local et ne peut employer d'autres professionnels. Un investisseur détient et dirige une société mauricienne qui peut embaucher, contracter et croître. Si le projet est une pratique exercée seul, le Self-Employed est plus simple et moins coûteux à maintenir. Si le projet est une entreprise avec des salariés et un nom propre, la voie Investisseur en est le fondement nécessaire.</p>
<p><strong>Le secteur.</strong> Le Self-Employed est réservé aux services. Le négoce, l'industrie, l'hôtellerie et la promotion immobilière relèvent par définition de l'Investisseur.</p>
<p><strong>Les obligations.</strong> Les deux comportent des conditions de revenus ou de chiffre d'affaires à partir de la troisième année, et plus élevées à partir de la cinquième pour le renouvellement : 2 et 3 millions MUR pour l'indépendant, 5 et 8 millions MUR pour l'investisseur. Les montants de l'investisseur sont plus élevés parce qu'on attend davantage d'une société, mais ceux de l'indépendant sont un revenu personnel et ne sont pas toujours plus faciles à atteindre.</p>
<p><strong>La famille.</strong> Les deux permis s'étendent au conjoint, aux enfants et aux parents en qualité de personnes à charge. Lorsque les deux conjoints seront actifs dans l'entreprise, la structure courante est un permis Investisseur pour l'un et un permis Professionnel pour l'autre, employé par la même société.</p>
<p>Le mauvais choix est rarement fatal, un titulaire pouvant changer de catégorie ensuite, mais il coûte du temps et une seconde demande. Le bon choix est généralement clair après une conversation sur ce à quoi ressemblera l'entreprise en troisième année.</p>
`,
  },

  "golden-visa-what-it-adds": {
    title: "Le Golden Visa : ce qu'il ajoute aux voies existantes",
    summary:
      "Maurice a annoncé un Golden Visa à 1 million USD ouvrant la voie à une demande de résidence permanente de vingt ans. Où il se situe par rapport aux permis existants, et à qui il s'adresse.",
    body: `
<p>Maurice a approuvé un Golden Visa en avril 2026 et l'a inscrit dans la loi par les mesures du Budget. Les directives de dépôt et la date d'entrée en vigueur sont encore attendues de l'Economic Development Board : ce qui suit est donc le cadre tel qu'annoncé, non le dispositif tel qu'appliqué.</p>
<p><strong>Sa forme.</strong> Un visa à entrées multiples pour une personne fortunée et sa famille proche, valable jusqu'à deux ans et renouvelable. Au dépôt, le titulaire s'engage par écrit à investir 1 million USD à Maurice dans les douze mois. Une fois l'investissement réalisé, il devient éligible pour demander un permis de résidence permanente de vingt ans. L'éligibilité n'est pas l'octroi, et la conversion n'est pas automatique. Le gouvernement a évoqué une centaine de bénéficiaires par an et un objectif de traitement de cinq jours ouvrés.</p>
<p><strong>Ce qui compte.</strong> Toute activité économique autre que l'achat d'un bien résidentiel dans les programmes immobiliers de l'EDB. La fintech, l'intelligence artificielle, les biotechnologies, les énergies renouvelables et la trésorerie internationale ont été citées comme secteurs d'intérêt. Un logement dans les programmes peut toujours être acquis, mais il se situe hors du million de dollars.</p>
<p><strong>Où il se situe.</strong> Maurice offre déjà la résidence par l'immobilier à 375 000 USD, un permis Investisseur à 100 000 USD assorti d'obligations de chiffre d'affaires, et un permis Retired Non-Citizen sur des transferts de 24 000 USD par an. Le Golden Visa demande plus de capital que tous ces dispositifs et ouvre en retour, sous un an, la possibilité de demander la résidence permanente, avec une liberté d'affectation du capital. Il ne confère pas le droit de travailler : l'attente est un investissement, non un emploi.</p>
<p><strong>À qui il s'adresse.</strong> À une famille disposant d'un capital à déployer, qui souhaite être à Maurice rapidement et détenir un permis de longue durée non lié à la conduite quotidienne d'une entreprise ni à la détention d'un bien précis. Pour un fondateur qui dirigera une société ici, le permis Investisseur reste plus adapté. Pour une personne de plus de 50 ans vivant de revenus de l'étranger, le permis Retired Non-Citizen reste le plus simple.</p>
<p>Les demandes passeront par un examen interinstitutionnel associant la Financial Crimes Commission, la Financial Intelligence Unit, la Financial Services Commission et la Banque de Maurice. L'origine du patrimoine sera examinée sérieusement. Nous publierons les exigences documentaires dès la parution des directives de l'EDB.</p>
`,
  },
};
