import type { Locale } from "@/lib/i18n";

const en = {
  nav: { consult: "Request a consultation", menu: "Menu", close: "Close", whatsapp: "WhatsApp", skip: "Skip to content" },
  footer: {
    tagline: "Clear guidance for living, investing and doing business in Mauritius.",
    legal: "start.mu is operated by Intrasia Corporate Services Limited, part of the Intrasia Group.",
    rights: "All rights reserved.",
    privacy: "Privacy policy",
    terms: "Terms",
    group: "Intrasia Group",
    columns: ["Residency", "Establishment", "Property", "Firm"],
  },
  cta: {
    heading: "Begin with a conversation",
    body: "The first consultation is by appointment and lasts an hour. You leave with a clear view of which route fits, what it will cost, and how long it will take.",
    button: "Request a consultation",
    residency: { heading: "Not sure this is the right route?", body: "Most people leave the first consultation with a different route from the one they arrived with. An hour, by appointment, and you leave with a clear view of which permit fits, what it will cost, and how long it will take." },
    establishment: { heading: "Tell us what the business will do", body: "The right structure follows from the activity, the owners and where the customers are. Describe those three things and we will set out the structure, the costs and the sequence in a written proposal." },
    property: { heading: "Before you reserve", body: "The buyer's position is decided at signature, not afterwards. If you are looking at a development, speak to us before the reservation deposit is paid and we will tell you what to examine." },
  },
  service: { glance: "At a glance", faq: "Questions we are asked", related: "Related", routes: "The routes", residency: "Residency", establishment: "Establishment", property: "Property" },
  index: { route: "Route", audience: "Who it is for", threshold: "Threshold", duration: "Duration", use: "Typical use", control: "Management and control", tax: "Tax position", offer: "What is on offer", status: "Status" },
  home: {
    eyebrow: "The private client practice of the Intrasia Group, in Mauritius",
    h1: "Residency, establishment, and the quieter work of settling into Mauritius.",
    finder: "Which route fits: four questions",
    bridgeH: "From first conversation to arrival",
    bridge: "We take care of the details so that the move, in practice, is not your project.",
    pillars: [
      { title: "Residency", href: "/residency", body: "Investor, self-employed, professional, retired, or through property acquisition. We advise on which permit fits, prepare the application, manage the submission with the Economic Development Board and the Passport and Immigration Office, and see it through to issuance. Dependents included.", link: "How we handle residency" },
      { title: "Establishment", href: "/establishment", body: "A Mauritian domestic company, incorporated and administered. A corporate bank account introduced and supported through onboarding. A registered office address and company secretary, held on our books. The structure your permit requires, operational from day one.", link: "How we handle establishment" },
      { title: "Concierge", href: "/concierge", body: "The arrangements that a permit and a company do not cover. Schools for the children. A home to rent or buy. Medical cover that works in Mauritius and abroad. Utilities, vehicles, household staff, a local accountant, introduced, set up, and quietly handed over.", link: "How we handle concierge" },
    ],
    routesH: "The routes, at a glance",
    routesBody: "Six ways into Mauritius, with the threshold that matters for each. The full comparison, including professional, innovator and dependent permits, is on the residency page.",
    routesLink: "See every route",
    howH: "How we work",
    steps: [
      { title: "A first conversation", body: "We begin by understanding what you are trying to do and why. Whether the move is driven by business, family, or retirement shapes everything that follows: the permit, the structure, the timing. The first consultation is by appointment and lasts an hour." },
      { title: "A considered proposal", body: "You receive a written proposal setting out the recommended path, the full scope of work, the fees, and the timeline. There are no hidden costs and no stages we have not priced. Most clients decide within a week." },
      { title: "The work, and what follows", body: "We handle the application, the incorporation, the banking, and the arrangements on the ground. Once you arrive, we remain available for the annual compliance, the Year 5 threshold, and the ordinary questions that come with living somewhere new." },
    ],
    mauritiusH: "Mauritius in practice",
    mauritius: [
      "A stable democracy with an independent judiciary, English and French in daily use, personal income tax that tops out at 20%, with a further 15% Fair Share Contribution above MUR 12 million in force to 30 June 2028, a remittance basis for foreign income, no capital gains tax, and direct flights to Johannesburg, Paris, London, Dubai and Singapore. Good international schools, reliable private healthcare, and a coastline you can live on.",
      "It is also a small island where approvals run to their own timetable, banks ask hard questions, and permit rules change with each Budget. The practical side is where most relocations go slowly. It is the side we handle.",
    ],
    mauritiusLink: "More on living and doing business here",
    notesH: "Recent notes",
    notesLink: "All notes",
    credibility: "start.mu is operated by Intrasia Corporate Services Limited, registered as a Company Secretary and Corporate Service Provider with the Mauritius Registrar of Companies and part of the Intrasia Group, with a presence in Mauritius, Singapore, Dubai, London and South Africa.",
  },
  insightsPage: {
    title: "Insights",
    meta: "Notes on residency, establishment, property and living in Mauritius from start.mu.",
    lead: "Notes on the permit rules as they change, on the practical side of establishing here, and on the questions clients ask most often.",
    empty: "The first notes are being prepared. In the meantime, the residency, establishment and property sections carry the current thresholds and the way each process works.",
    emptyLink: "Compare the residency routes",
    reviewed: "Last reviewed",
    categories: {
      Residency: "Residency",
      Establishment: "Establishment",
      Property: "Property",
      "Living in Mauritius": "Living in Mauritius",
    },
  },
  aboutPage: {
    metaTitle: "About start.mu, the private client practice of the Intrasia Group",
    meta: "start.mu helps investors, entrepreneurs and families with residency, occupation permits and company formation in Mauritius. Clear from the start.",
    title: "About start.mu",
    lead: "The private client practice of the Intrasia Group in Mauritius.",
    firmH: "The firm",
    firm: [
      "start.mu is the private client practice of the Intrasia Group in Mauritius, operated by Intrasia Corporate Services Limited. The name is short because our clients come from many languages, and a name they can say and type matters. The firm behind it, its registrations and its people are those of the group.",
      "We help individuals, families and businesses establish themselves in Mauritius, whether that means applying for residency, forming a company, buying a home or managing an operation that is already running.",
      "Behind the practice stands the Intrasia Group: a licensed management company, a licensed wealth manager, a compliance and regulatory technology arm and a real estate arm, with offices in Mauritius, Singapore, Dubai, London and South Africa. Work that needs a licensed management company, a compliance review, a view on another jurisdiction or a specialist we do not have in the room stays inside the group. Clients deal with one practice and get the resources of all of it.",
      "Our role is to make the process clear. We set out the requirements, prepare the documents and coordinate each step, from the first conversation through to approval and beyond. Before you commit to anything, you should understand what is required, what it will cost and how long it is likely to take.",
      "Our services in Mauritius are delivered through Intrasia Corporate Services Limited, which is registered as a Company Secretary and Corporate Service Provider with the Mauritius Registrar of Companies. We handle the application from start to finish, including all dealings with the Economic Development Board, the Passport and Immigration Office and other authorities.",
      "Where legal, tax, investment or regulated financial advice is required, we introduce clients to appropriately qualified professionals. For structures that require a licensed management company, we work with our sister company, Intrasia Management (Mauritius) Limited, which is licensed by the Financial Services Commission.",
    ],
    servicesH: "What we do",
    services: [
      "Investor, Professional, Self-Employed and Innovator Occupation Permit applications",
      "Retired Non-Citizen Residence Permit applications",
      "Residence permit applications connected to approved property purchases",
      "Golden Visa and Premium Visa applications",
      "Company incorporation and business registration",
      "Registered office, company secretary and resident director services",
      "Corporate and personal bank account applications",
      "Property acquisition under the approved schemes, including off-plan purchases",
      "Ongoing company administration, statutory compliance and EDB declarations",
      "Concierge: schools, housing, medical cover, vehicles and household",
    ],
    hermanRole: "General Manager, Intrasia Corporate Services",
    herman: [
      "Herman Suhirman leads the practice in Mauritius. He works with investors, entrepreneurs, professionals and families on company formation, licensing and regulatory approvals, residency and occupation permits, and cross-border structuring, and he leads the team that carries each engagement through.",
      "The approach is practical: establish what a route actually requires, confirm it with the authorities before anything is submitted, and move from decision to implementation without avoidable delay. Applications, incorporations, bank account openings and the dealings with the Economic Development Board and the Passport and Immigration Office are handled in-house, by people who do this work every week.",
      "His work reaches across the Intrasia Group. Through Intrasia Properties he is involved in the acquisition, development and structuring of commercial and residential real estate, and he works on compliance technology for know-your-client checks, enhanced due diligence and adverse media screening. That range matters here, because most of what clients bring to us sits where regulation, capital and real assets meet.",
      "His professional background spans Mauritius and Singapore, and he studied at the University of Melbourne.",
    ],
    leaRole: "Senior Client Executive",
    lea: [
      "Lea Permal is the day-to-day contact on most of our engagements. She prepares and files residence and occupation permit applications, handles incorporations, registered office and company secretarial work, and manages bank account openings and the correspondence with the Economic Development Board and the Passport and Immigration Office.",
      "She is the person who knows where a file stands, what the authority has asked for and what is still outstanding. Most clients speak to her more often than to anyone else here, and that is deliberate: the work moves faster when one person holds the whole picture.",
    ],
    groupH: "Part of the Intrasia Group",
    groupIntro:
      "start.mu is part of the Intrasia Group, an international group providing corporate, management, investment and financial services, with a presence in Mauritius, Singapore, Dubai, London and South Africa. Alongside this practice, the group comprises:",
    companies: [
      { name: "Intrasia Management (Mauritius) Limited", body: "the group's regulated management company in Mauritius, for structures that require one" },
      { name: "Intrasia Wealth Limited", body: "the group's wealth management company, present in Mauritius, Dubai, Singapore and South Africa. It is licensed by the Financial Services Commission (Mauritius) as an Investment Adviser (Unrestricted), licence no. IX24200006, and by the Financial Sector Conduct Authority (South Africa) as a Category 1 Adviser, licence no. 54955" },
      { name: "Intrasia Intelligence Solutions Limited", body: "the group's compliance and regulatory technology arm: sanctions and adverse media screening, know-your-client checks, enhanced due diligence and AML/CFT audits" },
      { name: "Intrasia Properties Ltd", href: "https://www.intrasiaproperties.com", body: "the group's real estate arm, which develops and manages its own commercial property portfolio, with interests in Mauritius, Singapore and Madagascar and office developments under way in Mauritius" },
    ],
    groupAfter:
      "This wider network lets us support clients whose business, family or investment interests reach beyond Mauritius. When further expertise is needed, we connect you with the right specialists inside the group or with independent professionals we have worked with before.",
    singaporeH: "Intrasia in Singapore",
    singapore:
      "Intrasia Corporate Services Pte Ltd supports start-ups and small to medium-sized businesses operating in Singapore with company secretarial services, accounting, tax support, payroll, human resources and general corporate administration.",
    singaporeLabel: "Singapore",
    ctaH: "Speak with us",
    ctaBody: "Tell us what you would like to achieve, and we will explain how we can help, what we need from you and what happens next.",
  },
  mauritiusPage: {
    title: "Mauritius in practice",
    meta: "Living and doing business in Mauritius: tax, law, language, schools, healthcare, banking, connectivity, and the practical side of relocating to the island.",
    lead: "A stable Indian Ocean democracy with a hybrid legal system, English and French in everyday use, a competitive tax regime, and a genuinely coastal lifestyle. It is also a small island where administrative processes can require time and patience. Both realities matter.",
    frameworkH: "The framework",
    caption: "Mauritius: tax, legal and practical framework",
    disclaimer: "Tax rates and treaty positions change. We are not tax advisers and introduce a Mauritian tax specialist where the position matters.",
    livingH: "Living here",
    living: [
      "The north is where many relocating families first look. Grand Baie and Pereybere offer beaches, restaurants and everyday convenience, and the golf-and-beach estates along that coast are among the island's best known. Inland around Piton, gated estates appeal to families who want quieter, greener surroundings with good access to schools and the motorway. The west, from Tamarin to Black River, is shaped by outdoor life, with the mountains behind and the lagoon in front: surfing, hiking and boating alongside established family neighbourhoods, and the island's one true marina development at Black River. Development has accelerated, so the region is more relaxed in character than uniformly quiet.",
      "The centre, particularly Moka and nearby Ebène, is the practical alternative to coastal living. Moka's residential neighbourhoods and Smart City developments put families close to several leading schools, major business districts, healthcare and shopping. The trade-off is distance from the beach; the advantages are convenience, a cooler upland climate and shorter everyday journeys.",
      "International schools follow the English, French or International Baccalaureate systems. Private healthcare is good and reasonably priced; complex cases are referred to South Africa, Réunion or Europe, which is why medical cover that works abroad matters. Domestic staff are affordable and widely employed. Driving is on the left, and a car is a necessity outside the towns.",
    ],
    businessH: "Doing business here",
    business: [
      "Mauritius is well regulated and it shows in the paperwork. Banks apply enhanced due diligence to non-residents. The Economic Development Board checks that permit holders meet their conditions, and its monitoring of permit conditions has teeth. The Registrar of Companies, the Mauritius Revenue Authority and the Financial Services Commission each expect their filings on time.",
      "None of this is difficult when it is handled from the start. Most of the difficulty we see arises from files that were prepared casually, structures that were not thought through, or thresholds that were not tracked. The practical side is where relocations go slowly, and it is the side we handle.",
    ],
    facts: [
      { label: "Personal income tax", value: "Progressive rates up to 20% following the 2023 reform. A Fair Share Contribution of 15% applies to leviable income above MUR 12 million, for the income years from 1 July 2025 to 30 June 2028. Leviable income adds dividends from resident companies to chargeable income, so Mauritian dividends that are otherwise exempt count towards the threshold. Foreign-source income is taxed on a remittance basis for residents" },
      { label: "Corporate tax", value: "15%, with partial exemptions for certain classes of income. No capital gains tax. No inheritance tax" },
      { label: "Tax residence", value: "183 days in a tax year, or 270 days over three consecutive years" },
      { label: "Double taxation agreements", value: "A network of more than 40 agreements in force, including with South Africa, France, the United Kingdom, Germany, India and China" },
      { label: "Legal system", value: "A hybrid of French civil law and English common law, with final appeal to the Judicial Committee of the Privy Council" },
      { label: "Languages", value: "English is the language of government and law. French is widely spoken. Mauritian Creole is the everyday language" },
      { label: "Currency", value: "Mauritian rupee, freely convertible, with no exchange controls" },
      { label: "Time zone", value: "GMT +4, which overlaps with Africa, Europe, the Gulf and Asia within a working day" },
      { label: "Flights", value: "Direct services to Johannesburg, Cape Town, Durban, Paris, London, Dubai, Mumbai, Singapore, Perth and Réunion" },
    ],
  },
  conciergePage: {
    title: "Concierge",
    meta: "The arrangements a permit and a company do not cover: schools, a home, medical cover, banking, vehicles, household staff and a local accountant, introduced and handed over by start.mu, the private client practice of the Intrasia Group.",
    metaTitle: "Concierge and relocation",
    lead: "The arrangements that a permit and a company do not cover. Introduced, set up, and quietly handed over, so that the move in practice is not your project.",
    requestH: "Available on request",
    request: [
      "Concierge is not included by default. It is arranged when a family asks for it, and what we take on is agreed with you and set out in the written proposal alongside the permit and establishment work.",
      "Ask early. Schools admit on their own cycles, and a lease, a bank account or medical cover is easier to arrange before arrival than after it, so the sooner we know what you need, the more of it can be in place on the day you land.",
      "We introduce and coordinate. The schools, the insurers, the landlords, the accountant and the household staff contract with the family directly, and we step back once each arrangement is working.",
    ],
    areas: [
      { title: "Schools", body: "Introductions to the international and private schools that fit the family, visits arranged, the admissions process managed, and the timing aligned with the permit so that places are secured before arrival." },
      { title: "A home", body: "Rental or purchase, in the areas that suit the family's life: near the schools, near the office, or on the coast. We shortlist, arrange viewings, review leases, and, for purchases, act for the buyer through the scheme process." },
      { title: "Medical cover", body: "Private health insurance that works in Mauritius and abroad, with the local clinics and specialists introduced. Medical examinations for the permit are arranged with the approved practitioners." },
      { title: "Banking and money", body: "Personal accounts opened, cards issued, the transfer of funds from abroad planned so that the permit conditions are met on time, and a local accountant introduced for the personal tax return." },
      { title: "Vehicles and utilities", body: "A car sourced, purchased or leased, registered and insured. Electricity, water, internet and mobile accounts opened in the family's name before the first night in the house." },
      { title: "Household", body: "Domestic staff introduced and engaged properly, with contracts and social security registration in order. A gardener, a pool company, a handyman: the people who make a house run." },
    ],
  },
  contactPage: {
    title: "Request a consultation",
    meta: "Contact start.mu in Mauritius to arrange a first consultation on residency, company establishment, property acquisition or relocation.",
    lead: "The first consultation is by appointment and lasts an hour, in person in Mauritius or by video call. Tell us a little about what you are trying to do and we will propose a time.",
    directlyH: "Directly",
    expectH: "What to expect",
    expect:
      "We reply within one working day. After the consultation you receive a written proposal setting out the recommended route, the scope of work, the fees and the timeline. There is no obligation and no charge for the proposal.",
  },
  form: {
    name: "Name",
    email: "Email",
    interest: "What you would like to discuss",
    message: "Message",
    placeholder: "Tell us what you are trying to do and roughly when. A few lines is enough.",
    send: "Send message",
    sending: "Sending",
    sentH: "Message received",
    sentBody: "We reply within one working day and will propose a time to speak.",
    privacyBefore: "We use what you send here to answer your enquiry and nothing else. Our ",
    privacyLink: "privacy policy",
    privacyAfter: " sets out how long we keep it and what you may ask us to do with it.",
    failed: "The message could not be sent.",
    interests: [
      "Residency permit",
      "Company establishment",
      "Property acquisition",
      "Golden Visa",
      "Concierge and relocation",
      "Something else",
    ],
  },
  establishmentPage: {
    title: "Establishment",
    lead: "A company incorporated and administered, a bank account open, a registered office and secretary on our books. The structure your permit or your business requires, operational from day one and kept in good standing after that.",
    whichH: "Which structure fits",
    adminH: "Administration",
    adminLead: "The services that keep a company and a permit in good standing, year after year.",
  },
  propertyPage: {
    title: "Property",
    lead: "A non-citizen may buy residential property in Mauritius within the schemes the Economic Development Board has approved, and, at USD 375,000 and above, may live here for as long as the property is held. The schemes differ in what they offer and in what to examine before buying. We act for the buyer only: we are not agents for any developer and take no commission from sellers.",
    comparedH: "The schemes, compared",
    sequenceH: "How a purchase proceeds",
    sequenceLead: "The sequence is the same under every scheme. Off-plan purchases add staged payments and a completion guarantee, which we cover separately.",
    vefaLink: "Off-plan and VEFA",
    actH: "Who we act for",
    act: [
      "We act for the buyer. We are not agents for any developer and we do not take commission from sellers. Our fee is agreed with the buyer in the written proposal, and our advice on a development, a guarantee or a payment schedule is given with only the buyer's position in mind.",
      "Where the buyer prefers to hold through a Mauritian company and trust, we set up the structure in parallel with the reservation so that the deed is not delayed.",
    ],
    sequence: [
      { title: "Reservation", body: "A reservation agreement with the developer or seller, with a deposit held by the notary." },
      { title: "EDB authorisation", body: "The buyer's application to the Economic Development Board for authorisation to acquire, with identity, source of funds and, where relevant, the structure through which the property will be held." },
      { title: "Deed", body: "The notarial deed of sale, or the VEFA deed for an off-plan unit, signed before a notary. Registration duty of 5% is paid by the buyer." },
      { title: "Registration and permit", body: "Registration of the deed, and for purchases at USD 375,000 and above, the residence permit application through the EDB." },
    ],
  },
  residencyPage: {
    title: "Residency",
    lead: "Eight routes into Mauritius, each with a different threshold, duration and set of conditions. The right one depends on what you are trying to do: run a business, work, retire, invest, or simply live here for a while first.",
    finder: "Not sure which? Four questions",
    compareH: "Every route, compared",
    chooseH: "Choosing between them",
    choose: [
      "Most people arrive with a route in mind and leave the first consultation with a different one. Someone who assumed they needed to buy property discovers the Retired Non-Citizen permit. A consultant who was going to incorporate finds the Self-Employed permit simpler. A founder who cannot commit USD 100,000 learns that the innovative start-up route has no minimum investment.",
      "The questions that decide it are practical. Will you run a business here or work for one? Are you over 50? Do you want to own a home in any case? How much capital are you prepared to commit, and how quickly do you need to be here? Our job is to ask them, and to say plainly which route fits.",
    ],
    alsoH: "Also in this section",
  },
  untranslated: "",
};

type Ui = typeof en;

const fr: Ui = {
  nav: { consult: "Prendre rendez-vous", menu: "Menu", close: "Fermer", whatsapp: "WhatsApp", skip: "Aller au contenu" },
  footer: {
    tagline: "Des conseils clairs pour vivre, investir et entreprendre à Maurice.",
    legal: "start.mu est exploité par Intrasia Corporate Services Limited, membre du Groupe Intrasia.",
    rights: "Tous droits réservés.",
    privacy: "Confidentialité",
    terms: "Conditions",
    group: "Groupe Intrasia",
    columns: ["Résidence", "Établissement", "Immobilier", "Le cabinet"],
  },
  cta: {
    heading: "Tout commence par une conversation",
    body: "La première consultation se fait sur rendez-vous et dure une heure. Vous en repartez avec une vue claire de la voie qui vous convient, de son coût et du temps qu'elle prendra.",
    button: "Prendre rendez-vous",
    residency: { heading: "Pas certain que ce soit la bonne voie ?", body: "La plupart des personnes quittent la première consultation avec une voie différente de celle qu'elles avaient en tête. Une heure, sur rendez-vous, et vous savez quel permis vous convient, ce qu'il coûtera et combien de temps il prendra." },
    establishment: { heading: "Dites-nous ce que fera l'entreprise", body: "La bonne structure découle de l'activité, des associés et de l'emplacement des clients. Décrivez ces trois éléments et nous vous proposerons la structure, les coûts et la séquence dans une proposition écrite." },
    property: { heading: "Avant de réserver", body: "La position de l'acheteur se décide à la signature, pas après. Si vous regardez un programme, parlez-nous avant de verser le dépôt de réservation et nous vous dirons ce qu'il faut examiner." },
  },
  service: { glance: "L'essentiel", faq: "Les questions qu'on nous pose", related: "Voir aussi", routes: "Les voies", residency: "Résidence", establishment: "Établissement", property: "Immobilier" },
  index: { route: "Voie", audience: "Pour qui", threshold: "Seuil", duration: "Durée", use: "Usage typique", control: "Gestion et contrôle", tax: "Régime fiscal", offer: "Ce qui est proposé", status: "Statut" },
  home: {
    eyebrow: "Le cabinet de clientèle privée du Groupe Intrasia, à Maurice",
    h1: "La résidence, l'établissement, et le travail discret de s'installer à Maurice.",
    finder: "Quelle voie vous convient : quatre questions",
    bridgeH: "De la première conversation à l'arrivée",
    bridge: "Nous nous occupons des détails pour que l'installation, en pratique, ne soit pas votre projet.",
    pillars: [
      { title: "Résidence", href: "/residency", body: "Investisseur, indépendant, professionnel, retraité, ou par l'acquisition d'un bien immobilier. Nous déterminons le permis qui convient, préparons le dossier, gérons la soumission auprès de l'Economic Development Board et du Passport and Immigration Office, et suivons le dossier jusqu'à la délivrance. Personnes à charge comprises.", link: "Comment nous traitons la résidence" },
      { title: "Établissement", href: "/establishment", body: "Une société domestique mauricienne, constituée et administrée. Un compte bancaire professionnel, présenté et accompagné jusqu'à l'ouverture. Un siège social et un secrétaire de société, tenus dans nos livres. La structure que votre permis exige, opérationnelle dès le premier jour.", link: "Comment nous traitons l'établissement" },
      { title: "Conciergerie", href: "/concierge", body: "Ce qu'un permis et une société ne couvrent pas. Les écoles pour les enfants. Un logement à louer ou à acheter. Une couverture médicale valable à Maurice et à l'étranger. Les services, les véhicules, le personnel de maison, un comptable local : présentés, mis en place et remis en main propre.", link: "Comment nous traitons la conciergerie" },
    ],
    routesH: "Les voies, en un coup d'œil",
    routesBody: "Six manières de s'établir à Maurice, avec le seuil qui compte pour chacune. La comparaison complète, y compris les permis professionnel, innovateur et pour personnes à charge, se trouve sur la page Résidence.",
    routesLink: "Voir toutes les voies",
    howH: "Notre méthode",
    steps: [
      { title: "Une première conversation", body: "Nous commençons par comprendre ce que vous voulez faire et pourquoi. Qu'un déménagement soit motivé par les affaires, la famille ou la retraite détermine tout ce qui suit : le permis, la structure, le calendrier. La première consultation se fait sur rendez-vous et dure une heure." },
      { title: "Une proposition réfléchie", body: "Vous recevez une proposition écrite précisant la voie recommandée, l'étendue du travail, les honoraires et le calendrier. Pas de coûts cachés, pas d'étapes non chiffrées. La plupart des clients décident dans la semaine." },
      { title: "Le travail, et la suite", body: "Nous gérons le dossier, la constitution de la société, la banque et les démarches sur place. Une fois arrivé, nous restons disponibles pour la conformité annuelle, le seuil de la cinquième année et les questions ordinaires qu'entraîne la vie dans un nouveau pays." },
    ],
    mauritiusH: "Maurice, en pratique",
    mauritius: [
      "Une démocratie stable dotée d'une justice indépendante, l'anglais et le français au quotidien, un impôt sur le revenu plafonné à 20 %, auquel s'ajoute une Fair Share Contribution de 15 % au-delà de 12 millions MUR, en vigueur jusqu'au 30 juin 2028, l'imposition des revenus étrangers sur la base du rapatriement, pas d'impôt sur les plus-values, et des vols directs vers Johannesburg, Paris, Londres, Dubaï et Singapour. De bonnes écoles internationales, un secteur privé de santé fiable et un littoral où l'on peut vivre.",
      "C'est aussi une petite île où les procédures suivent leur propre calendrier, où les banques posent des questions difficiles et où les règles de permis changent à chaque Budget. Le côté pratique est là où la plupart des installations ralentissent. C'est le côté que nous prenons en charge.",
    ],
    mauritiusLink: "En savoir plus sur la vie et les affaires à Maurice",
    notesH: "Notes récentes",
    notesLink: "Toutes les notes",
    credibility: "start.mu est exploité par Intrasia Corporate Services Limited, enregistrée comme Company Secretary et Corporate Service Provider auprès du Registrar of Companies de Maurice, et fait partie du Groupe Intrasia, présent à Maurice, à Singapour, à Dubaï, à Londres et en Afrique du Sud.",
  },
  insightsPage: {
    title: "Publications",
    meta: "Notes sur la résidence, l'établissement, l'immobilier et la vie à Maurice, par start.mu.",
    lead: "Des notes sur les règles des permis à mesure qu'elles évoluent, sur l'aspect pratique de l'installation ici, et sur les questions que les clients posent le plus souvent.",
    empty: "Les premières notes sont en préparation. Entre-temps, les sections résidence, établissement et immobilier présentent les seuils actuels et le déroulement de chaque procédure.",
    emptyLink: "Comparer les voies de résidence",
    reviewed: "Dernière révision",
    categories: {
      Residency: "Résidence",
      Establishment: "Établissement",
      Property: "Immobilier",
      "Living in Mauritius": "Vivre à Maurice",
    },
  },
  aboutPage: {
    metaTitle: "À propos de start.mu, le cabinet de clientèle privée du Groupe Intrasia",
    meta: "start.mu accompagne investisseurs, entrepreneurs et familles pour la résidence, les Occupation Permits et la création de sociétés à Maurice. Clair dès le départ.",
    title: "À propos de start.mu",
    lead: "Le cabinet de clientèle privée du Groupe Intrasia à Maurice.",
    firmH: "Le cabinet",
    firm: [
      "start.mu est le cabinet de clientèle privée du Groupe Intrasia à Maurice, exploité par Intrasia Corporate Services Limited. Le nom est court parce que nos clients viennent de plusieurs langues, et un nom qu'ils peuvent prononcer et saisir compte. Le cabinet qui se tient derrière, ses agréments et ses équipes sont ceux du groupe.",
      "Nous aidons les particuliers, les familles et les entreprises à s'établir à Maurice, qu'il s'agisse de demander la résidence, de constituer une société, d'acheter un logement ou de gérer une activité déjà en place.",
      "Derrière le cabinet se tient le Groupe Intrasia : une management company agréée, un gestionnaire de patrimoine agréé, un pôle conformité et technologie réglementaire et un pôle immobilier, avec des bureaux à Maurice, Singapour, Dubaï, Londres et en Afrique du Sud. Ce qui exige une management company agréée, une revue de conformité, un avis sur une autre juridiction ou un spécialiste dont nous ne disposons pas sur place reste à l'intérieur du groupe. Le client s'adresse à un seul cabinet et dispose des ressources de l'ensemble.",
      "Notre rôle est de rendre la procédure claire. Nous exposons les exigences, préparons les documents et coordonnons chaque étape, de la première conversation jusqu'à l'approbation et au-delà. Avant de vous engager, vous devez comprendre ce qui est exigé, ce que cela coûtera et le temps que cela prendra vraisemblablement.",
      "Nos prestations à Maurice sont délivrées par Intrasia Corporate Services Limited, enregistrée comme Company Secretary et Corporate Service Provider auprès du Registrar of Companies mauricien. Nous traitons le dossier de bout en bout, y compris l'ensemble des échanges avec l'Economic Development Board, le Passport and Immigration Office et les autres autorités.",
      "Lorsqu'un conseil juridique, fiscal, en investissement ou financier réglementé est nécessaire, nous présentons nos clients à des professionnels dûment qualifiés. Pour les structures qui requièrent une management company agréée, nous travaillons avec notre société sœur, Intrasia Management (Mauritius) Limited, agréée par la Financial Services Commission.",
    ],
    servicesH: "Ce que nous faisons",
    services: [
      "Demandes d'Occupation Permit Investisseur, Professionnel, Self-Employed et Innovateur",
      "Demandes de permis de résidence Retired Non-Citizen",
      "Demandes de permis de résidence liées à un achat immobilier agréé",
      "Demandes de Golden Visa et de Premium Visa",
      "Constitution de sociétés et immatriculation d'activités",
      "Siège social, company secretary et services d'administrateur résident",
      "Demandes d'ouverture de comptes bancaires professionnels et personnels",
      "Acquisition immobilière dans les programmes agréés, y compris l'achat sur plan",
      "Administration courante des sociétés, conformité statutaire et déclarations à l'EDB",
      "Conciergerie : écoles, logement, couverture médicale, véhicules et maison",
    ],
    hermanRole: "Directeur général, Intrasia Corporate Services",
    herman: [
      "Herman Suhirman dirige le cabinet à Maurice. Il accompagne investisseurs, entrepreneurs, professionnels et familles sur la constitution de sociétés, les licences et agréments réglementaires, la résidence et les Occupation Permits, ainsi que les structurations transfrontalières, et il dirige l'équipe qui mène chaque dossier à son terme.",
      "L'approche est pratique : établir ce qu'une voie exige réellement, le confirmer auprès des autorités avant tout dépôt, et passer de la décision à la mise en œuvre sans délai évitable. Les demandes, les constitutions de sociétés, les ouvertures de comptes et les échanges avec l'Economic Development Board et le Passport and Immigration Office sont traités en interne, par des personnes qui font ce travail chaque semaine.",
      "Son activité s'étend à l'ensemble du Groupe Intrasia. Via Intrasia Properties, il intervient dans l'acquisition, le développement et la structuration d'actifs immobiliers commerciaux et résidentiels, et il travaille sur des technologies de conformité pour les vérifications d'identité, la diligence renforcée et la veille sur les médias défavorables. Cette étendue compte ici, car l'essentiel de ce que nos clients nous apportent se situe à la rencontre de la réglementation, du capital et des actifs réels.",
      "Son parcours professionnel couvre Maurice et Singapour, et il a étudié à l'Université de Melbourne.",
    ],
    leaRole: "Senior Client Executive",
    lea: [
      "Lea Permal est l'interlocutrice au quotidien sur la plupart de nos dossiers. Elle prépare et dépose les demandes de permis de résidence et d'Occupation Permit, traite les constitutions de sociétés, le siège social et le secrétariat juridique, et gère les ouvertures de comptes bancaires ainsi que la correspondance avec l'Economic Development Board et le Passport and Immigration Office.",
      "C'est elle qui sait où en est un dossier, ce que l'autorité a demandé et ce qui reste à fournir. La plupart des clients lui parlent plus souvent qu'à quiconque ici, et c'est délibéré : le travail avance plus vite lorsqu'une seule personne a la vue d'ensemble.",
    ],
    groupH: "Membre du Groupe Intrasia",
    groupIntro:
      "start.mu fait partie du Groupe Intrasia, un groupe international de services aux entreprises, de gestion, d'investissement et de services financiers, présent à Maurice, Singapour, Dubaï, Londres et en Afrique du Sud. Aux côtés de ce cabinet, le groupe comprend :",
    companies: [
      { name: "Intrasia Management (Mauritius) Limited", body: "la management company réglementée du groupe à Maurice, pour les structures qui en exigent une" },
      { name: "Intrasia Wealth Limited", body: "la société de gestion de patrimoine du groupe, présente à Maurice, Dubaï, Singapour et en Afrique du Sud. Elle est agréée par la Financial Services Commission (Maurice) en qualité d'Investment Adviser (Unrestricted), licence n° IX24200006, et par la Financial Sector Conduct Authority (Afrique du Sud) en qualité de Category 1 Adviser, licence n° 54955" },
      { name: "Intrasia Intelligence Solutions Limited", body: "le pôle conformité et technologie réglementaire du groupe : criblage des sanctions et des médias défavorables, vérifications d'identité, diligence renforcée et audits LBC/FT" },
      { name: "Intrasia Properties Ltd", href: "https://www.intrasiaproperties.com", body: "le pôle immobilier du groupe, qui développe et gère son propre portefeuille d'actifs commerciaux, avec des intérêts à Maurice, à Singapour et à Madagascar et des programmes de bureaux en cours à Maurice" },
    ],
    groupAfter:
      "Ce réseau élargi nous permet d'accompagner des clients dont les intérêts professionnels, familiaux ou patrimoniaux dépassent Maurice. Lorsqu'une expertise supplémentaire est nécessaire, nous vous mettons en relation avec les bons spécialistes au sein du groupe ou avec des professionnels indépendants avec lesquels nous avons déjà travaillé.",
    singaporeH: "Intrasia à Singapour",
    singapore:
      "Intrasia Corporate Services Pte Ltd accompagne les start-up et les petites et moyennes entreprises opérant à Singapour : secrétariat juridique, comptabilité, assistance fiscale, paie, ressources humaines et administration générale.",
    singaporeLabel: "Singapour",
    ctaH: "Parlons-en",
    ctaBody: "Dites-nous ce que vous souhaitez accomplir, et nous vous expliquerons comment nous pouvons aider, ce dont nous avons besoin de votre part et ce qui se passe ensuite.",
  },
  mauritiusPage: {
    title: "Maurice en pratique",
    meta: "Vivre et entreprendre à Maurice : fiscalité, droit, langues, écoles, santé, banque, connexions aériennes et l'aspect pratique d'une installation sur l'île.",
    lead: "Une démocratie stable de l'océan Indien, au système juridique hybride, où l'anglais et le français s'emploient au quotidien, avec une fiscalité compétitive et une vie véritablement tournée vers la mer. C'est aussi une petite île où les démarches administratives peuvent demander du temps et de la patience. Ces deux réalités comptent.",
    frameworkH: "Le cadre",
    caption: "Maurice : cadre fiscal, juridique et pratique",
    disclaimer: "Les taux et les positions conventionnelles évoluent. Nous ne sommes pas conseils fiscaux et vous présentons un spécialiste mauricien lorsque la question le justifie.",
    livingH: "Vivre ici",
    living: [
      "Le nord est la première zone que regardent beaucoup de familles qui s'installent. Grand Baie et Pereybère offrent les plages, les restaurants et la commodité du quotidien, et les domaines golf et plage de cette côte comptent parmi les plus connus de l'île. Plus à l'intérieur, autour de Piton, les domaines sécurisés séduisent les familles qui cherchent un cadre plus calme et plus vert, avec un bon accès aux écoles et à l'autoroute. L'ouest, de Tamarin à Rivière Noire, est façonné par la vie au grand air, la montagne derrière et le lagon devant : surf, randonnée et navigation, aux côtés de quartiers familiaux établis et de la seule véritable marina résidentielle de l'île, à Rivière Noire. La construction s'est accélérée : la région est plus détendue par son caractère qu'uniformément calme.",
      "Le centre, en particulier Moka et Ébène toute proche, est l'alternative pratique à la vie côtière. Les quartiers résidentiels de Moka et les projets Smart City placent les familles à proximité de plusieurs grandes écoles, des principaux quartiers d'affaires, des soins et des commerces. La contrepartie est l'éloignement de la plage ; les avantages sont la commodité, un climat plus frais sur les hauteurs et des trajets quotidiens plus courts.",
      "Les écoles internationales suivent le système anglais, français ou le Baccalauréat International. La santé privée est de bon niveau et raisonnablement tarifée ; les cas complexes sont orientés vers l'Afrique du Sud, La Réunion ou l'Europe, d'où l'importance d'une couverture valable à l'étranger. Le personnel de maison est abordable et largement employé. On roule à gauche, et la voiture est indispensable hors des villes.",
    ],
    businessH: "Entreprendre ici",
    business: [
      "Maurice est bien réglementée, et cela se voit dans les formalités. Les banques appliquent une vigilance renforcée aux non-résidents. L'Economic Development Board vérifie que les titulaires de permis respectent leurs conditions, et son suivi n'est pas de pure forme. Le Registrar of Companies, la Mauritius Revenue Authority et la Financial Services Commission attendent chacun leurs déclarations dans les délais.",
      "Rien de tout cela n'est difficile lorsque c'est pris en main dès le départ. La plupart des difficultés que nous voyons viennent de dossiers préparés à la légère, de structures mal pensées ou de seuils qui n'ont pas été suivis. C'est sur l'aspect pratique que les installations s'enlisent, et c'est cet aspect que nous prenons en charge.",
    ],
    facts: [
      { label: "Impôt sur le revenu des personnes physiques", value: "Taux progressifs jusqu'à 20 % depuis la réforme de 2023. Une Fair Share Contribution de 15 % s'applique au leviable income supérieur à 12 millions MUR, pour les années fiscales du 1er juillet 2025 au 30 juin 2028. Le leviable income ajoute au revenu imposable les dividendes de sociétés résidentes : les dividendes mauriciens autrement exonérés comptent donc dans le seuil. Les revenus de source étrangère des résidents sont imposés sur une base de remise" },
      { label: "Impôt sur les sociétés", value: "15 %, avec des exonérations partielles pour certaines catégories de revenus. Pas d'impôt sur les plus-values. Pas de droits de succession" },
      { label: "Résidence fiscale", value: "183 jours au cours d'une année fiscale, ou 270 jours sur trois années consécutives" },
      { label: "Conventions fiscales", value: "Un réseau de plus de 40 conventions en vigueur, dont avec l'Afrique du Sud, la France, le Royaume-Uni, l'Allemagne, l'Inde et la Chine" },
      { label: "Système juridique", value: "Un système hybride de droit civil français et de common law anglaise, avec appel ultime devant le Comité judiciaire du Conseil privé" },
      { label: "Langues", value: "L'anglais est la langue de l'administration et du droit. Le français est largement parlé. Le créole mauricien est la langue du quotidien" },
      { label: "Monnaie", value: "La roupie mauricienne, librement convertible, sans contrôle des changes" },
      { label: "Fuseau horaire", value: "GMT +4, qui recoupe l'Afrique, l'Europe, le Golfe et l'Asie dans une même journée de travail" },
      { label: "Vols", value: "Liaisons directes vers Johannesburg, Le Cap, Durban, Paris, Londres, Dubaï, Bombay, Singapour, Perth et La Réunion" },
    ],
  },
  conciergePage: {
    title: "Conciergerie",
    meta: "Ce qu'un permis et une société ne couvrent pas : écoles, logement, couverture médicale, banque, véhicules, personnel de maison et comptable local, présentés et mis en place par start.mu, le cabinet de clientèle privée du Groupe Intrasia.",
    metaTitle: "Conciergerie et installation",
    lead: "Ce qu'un permis et une société ne couvrent pas. Présenté, mis en place et remis discrètement, pour que l'installation, en pratique, ne devienne pas votre projet.",
    requestH: "Sur demande",
    request: [
      "La conciergerie n'est pas comprise d'office. Elle est mise en place lorsqu'une famille la demande, et ce que nous prenons en charge est convenu avec vous et précisé dans la proposition écrite, aux côtés du permis et de la constitution de société.",
      "Demandez tôt. Les écoles admettent selon leur propre calendrier, et un bail, un compte bancaire ou une couverture médicale se préparent plus facilement avant l'arrivée qu'après : plus tôt nous connaissons vos besoins, plus de choses seront en place le jour où vous atterrissez.",
      "Nous présentons et coordonnons. Les écoles, les assureurs, les bailleurs, le comptable et le personnel de maison contractent directement avec la famille, et nous nous retirons dès que chaque dispositif fonctionne.",
    ],
    areas: [
      { title: "Écoles", body: "Mise en relation avec les écoles internationales et privées qui conviennent à la famille, visites organisées, procédure d'admission suivie, et calendrier aligné sur le permis afin que les places soient acquises avant l'arrivée." },
      { title: "Un logement", body: "Location ou achat, dans les zones qui correspondent à la vie de la famille : près des écoles, près du bureau ou sur la côte. Nous établissons une sélection, organisons les visites, examinons les baux et, pour les acquisitions, agissons pour l'acquéreur tout au long de la procédure." },
      { title: "Couverture médicale", body: "Une assurance santé privée valable à Maurice et à l'étranger, avec la présentation des cliniques et des spécialistes locaux. Les examens médicaux exigés pour le permis sont organisés auprès des praticiens agréés." },
      { title: "Banque et transferts", body: "Comptes personnels ouverts, cartes émises, transferts de fonds depuis l'étranger planifiés pour que les conditions du permis soient respectées dans les délais, et présentation d'un comptable local pour la déclaration de revenus." },
      { title: "Véhicules et services", body: "Une voiture recherchée, achetée ou louée, immatriculée et assurée. Électricité, eau, internet et téléphonie ouverts au nom de la famille avant la première nuit dans la maison." },
      { title: "Maison", body: "Personnel de maison présenté et employé dans les règles, avec contrats et affiliation à la sécurité sociale. Un jardinier, une société d'entretien de piscine, un homme à tout faire : les personnes qui font tourner une maison." },
    ],
  },
  contactPage: {
    title: "Prendre rendez-vous",
    meta: "Contactez start.mu à Maurice pour convenir d'un premier entretien sur la résidence, la création de société, l'acquisition immobilière ou l'installation.",
    lead: "Le premier entretien se tient sur rendez-vous et dure une heure, à Maurice ou en visioconférence. Dites-nous en quelques mots ce que vous cherchez à faire et nous vous proposerons un créneau.",
    directlyH: "Directement",
    expectH: "Ce qui suit",
    expect:
      "Nous répondons sous un jour ouvré. À l'issue de l'entretien, vous recevez une proposition écrite précisant la voie recommandée, l'étendue de la mission, les honoraires et le calendrier. Elle est sans engagement et sans frais.",
  },
  form: {
    name: "Nom",
    email: "E-mail",
    interest: "Ce dont vous souhaitez parler",
    message: "Message",
    placeholder: "Dites-nous ce que vous cherchez à faire et à quel horizon. Quelques lignes suffisent.",
    send: "Envoyer le message",
    sending: "Envoi en cours",
    sentH: "Message bien reçu",
    sentBody: "Nous répondons sous un jour ouvré et vous proposerons un créneau pour échanger.",
    privacyBefore: "Nous utilisons ce que vous envoyez ici pour répondre à votre demande, et rien d'autre. Notre ",
    privacyLink: "politique de confidentialité",
    privacyAfter: " indique combien de temps nous le conservons et ce que vous pouvez nous demander d'en faire.",
    failed: "Le message n'a pas pu être envoyé.",
    interests: [
      "Permis de résidence",
      "Création de société",
      "Acquisition immobilière",
      "Golden Visa",
      "Conciergerie et installation",
      "Autre chose",
    ],
  },
  establishmentPage: {
    title: "Établissement",
    lead: "Une société constituée et administrée, un compte bancaire ouvert, un siège social et un company secretary tenus par nos soins. La structure qu'exige votre permis ou votre activité, opérationnelle dès le premier jour et maintenue en règle ensuite.",
    whichH: "Quelle structure vous convient",
    adminH: "Administration",
    adminLead: "Les prestations qui maintiennent une société et un permis en règle, année après année.",
  },
  propertyPage: {
    title: "Immobilier",
    lead: "Un non-citoyen peut acquérir un bien résidentiel à Maurice dans le cadre des programmes agréés par l'Economic Development Board et, à partir de 375 000 USD, y résider tant que le bien est détenu. Les programmes diffèrent par ce qu'ils offrent et par ce qu'il faut examiner avant d'acheter. Nous agissons pour l'acquéreur seul : nous ne sommes agents d'aucun promoteur et ne percevons aucune commission des vendeurs.",
    comparedH: "Les programmes, comparés",
    sequenceH: "Le déroulement d'une acquisition",
    sequenceLead: "La séquence est la même dans tous les programmes. L'achat sur plan ajoute des paiements échelonnés et une garantie d'achèvement, que nous traitons séparément.",
    vefaLink: "Achat sur plan et VEFA",
    actH: "Pour qui nous agissons",
    act: [
      "Nous agissons pour l'acquéreur. Nous ne sommes agents d'aucun promoteur et ne percevons aucune commission des vendeurs. Nos honoraires sont convenus avec l'acquéreur dans la proposition écrite, et nos conseils sur un programme, une garantie ou un échéancier sont donnés en ne considérant que la position de l'acquéreur.",
      "Lorsque l'acquéreur préfère détenir par une société mauricienne et un trust, nous mettons la structure en place en parallèle de la réservation afin que l'acte ne soit pas retardé.",
    ],
    sequence: [
      { title: "Réservation", body: "Un contrat de réservation avec le promoteur ou le vendeur, le dépôt étant séquestré chez le notaire." },
      { title: "Autorisation de l'EDB", body: "La demande de l'acquéreur auprès de l'Economic Development Board en vue d'être autorisé à acquérir, avec l'identité, l'origine des fonds et, le cas échéant, la structure par laquelle le bien sera détenu." },
      { title: "Acte", body: "L'acte notarié de vente, ou l'acte de VEFA pour un bien sur plan, signé devant notaire. Le droit d'enregistrement de 5 % est acquitté par l'acquéreur." },
      { title: "Enregistrement et permis", body: "L'enregistrement de l'acte et, pour les acquisitions à partir de 375 000 USD, la demande de permis de résidence auprès de l'EDB." },
    ],
  },
  residencyPage: {
    title: "Résidence",
    lead: "Huit voies pour s'établir à Maurice, chacune avec son seuil, sa durée et ses conditions. La bonne dépend de ce que vous voulez faire : diriger une entreprise, travailler, prendre votre retraite, investir, ou simplement vivre ici quelque temps d'abord.",
    finder: "Vous hésitez ? Quatre questions",
    compareH: "Toutes les voies, comparées",
    chooseH: "Choisir entre elles",
    choose: [
      "La plupart des gens arrivent avec une voie en tête et repartent de la première consultation avec une autre. Celui qui pensait devoir acheter un bien découvre le permis de retraité. Le consultant qui allait constituer une société trouve le permis d'indépendant plus simple. Le fondateur qui ne peut pas engager 100 000 USD apprend que la voie des start-ups innovantes n'exige aucun investissement minimum.",
      "Les questions qui décident sont pratiques. Dirigerez-vous une entreprise ici ou travaillerez-vous pour l'une d'elles ? Avez-vous plus de 50 ans ? Voulez-vous de toute façon posséder un logement ? Quel capital êtes-vous prêt à engager, et à quelle échéance devez-vous être ici ? Notre rôle est de les poser, et de dire clairement quelle voie convient.",
    ],
    alsoH: "Également dans cette section",
  },
  untranslated: "Cette page est disponible en anglais pour le moment. La version française suit.",
};

const de: Ui = {
  nav: { consult: "Beratungsgespräch vereinbaren", menu: "Menü", close: "Schließen", whatsapp: "WhatsApp", skip: "Zum Inhalt" },
  footer: {
    tagline: "Klare Orientierung für Leben, Investieren und Unternehmen auf Mauritius.",
    legal: "start.mu wird von Intrasia Corporate Services Limited betrieben, einem Unternehmen der Intrasia Group.",
    rights: "Alle Rechte vorbehalten.",
    privacy: "Datenschutz",
    terms: "Nutzungsbedingungen",
    group: "Intrasia Group",
    columns: ["Aufenthalt", "Gründung", "Immobilien", "Kanzlei"],
  },
  cta: {
    heading: "Am Anfang steht ein Gespräch",
    body: "Das erste Beratungsgespräch findet nach Vereinbarung statt und dauert eine Stunde. Sie gehen mit einer klaren Vorstellung davon, welcher Weg passt, was er kostet und wie lange er dauert.",
    button: "Beratungsgespräch vereinbaren",
    residency: { heading: "Nicht sicher, ob das der richtige Weg ist?", body: "Die meisten verlassen das erste Gespräch mit einem anderen Weg als dem, mit dem sie gekommen sind. Eine Stunde nach Vereinbarung, und Sie wissen, welche Genehmigung passt, was sie kostet und wie lange sie dauert." },
    establishment: { heading: "Sagen Sie uns, was das Unternehmen tun wird", body: "Die richtige Struktur ergibt sich aus der Tätigkeit, den Eigentümern und dem Sitz der Kunden. Beschreiben Sie diese drei Punkte, und wir legen Struktur, Kosten und Ablauf in einem schriftlichen Angebot dar." },
    property: { heading: "Vor der Reservierung", body: "Die Position des Käufers wird bei der Unterzeichnung entschieden, nicht danach. Wenn Sie ein Projekt im Blick haben, sprechen Sie mit uns, bevor die Reservierungsanzahlung fließt, und wir sagen Ihnen, worauf zu achten ist." },
  },
  service: { glance: "Auf einen Blick", faq: "Häufige Fragen", related: "Verwandte Themen", routes: "Die Wege", residency: "Aufenthalt", establishment: "Gründung", property: "Immobilien" },
  index: { route: "Weg", audience: "Für wen", threshold: "Schwelle", duration: "Dauer", use: "Typische Verwendung", control: "Leitung und Kontrolle", tax: "Steuerliche Stellung", offer: "Angebot", status: "Status" },
  home: {
    eyebrow: "Die Private-Client-Praxis der Intrasia Group auf Mauritius",
    h1: "Aufenthalt, Gründung und die stille Arbeit des Ankommens auf Mauritius.",
    finder: "Welcher Weg passt: vier Fragen",
    bridgeH: "Vom ersten Gespräch bis zur Ankunft",
    bridge: "Wir kümmern uns um die Details, damit der Umzug in der Praxis nicht Ihr Projekt ist.",
    pillars: [
      { title: "Aufenthalt", href: "/residency", body: "Investor, Selbständiger, Angestellter, Ruheständler oder über den Erwerb einer Immobilie. Wir beraten, welche Genehmigung passt, bereiten den Antrag vor, führen das Verfahren beim Economic Development Board und beim Passport and Immigration Office und begleiten es bis zur Erteilung. Familienangehörige eingeschlossen.", link: "So begleiten wir den Aufenthalt" },
      { title: "Gründung", href: "/establishment", body: "Eine mauritische Domestic Company, gegründet und verwaltet. Ein Geschäftskonto, eingeführt und bis zur Eröffnung begleitet. Ein eingetragener Sitz und ein Company Secretary, in unseren Büchern geführt. Die Struktur, die Ihre Genehmigung verlangt, vom ersten Tag an einsatzbereit.", link: "So begleiten wir die Gründung" },
      { title: "Concierge", href: "/concierge", body: "Was Genehmigung und Gesellschaft nicht abdecken. Schulen für die Kinder. Ein Haus zur Miete oder zum Kauf. Eine Krankenversicherung, die auf Mauritius und im Ausland gilt. Versorger, Fahrzeuge, Hauspersonal, ein Buchhalter vor Ort: vermittelt, eingerichtet und still übergeben.", link: "So begleiten wir den Concierge-Service" },
    ],
    routesH: "Die Wege auf einen Blick",
    routesBody: "Sechs Wege nach Mauritius, mit der jeweils maßgeblichen Schwelle. Der vollständige Vergleich, einschließlich der Genehmigungen für Angestellte, Innovatoren und Familienangehörige, findet sich auf der Seite Aufenthalt.",
    routesLink: "Alle Wege ansehen",
    howH: "Wie wir arbeiten",
    steps: [
      { title: "Ein erstes Gespräch", body: "Wir beginnen damit, zu verstehen, was Sie vorhaben und warum. Ob der Umzug geschäftlich, familiär oder durch den Ruhestand motiviert ist, bestimmt alles Weitere: die Genehmigung, die Struktur, den Zeitplan. Das erste Gespräch findet nach Vereinbarung statt und dauert eine Stunde." },
      { title: "Ein durchdachtes Angebot", body: "Sie erhalten ein schriftliches Angebot mit dem empfohlenen Weg, dem vollständigen Leistungsumfang, den Honoraren und dem Zeitplan. Keine versteckten Kosten, keine unbezifferten Schritte. Die meisten Mandanten entscheiden innerhalb einer Woche." },
      { title: "Die Arbeit, und was folgt", body: "Wir übernehmen den Antrag, die Gründung, die Bank und die Vorkehrungen vor Ort. Nach Ihrer Ankunft bleiben wir für die jährlichen Pflichten, die Schwelle im fünften Jahr und die gewöhnlichen Fragen des Lebens in einem neuen Land erreichbar." },
    ],
    mauritiusH: "Mauritius in der Praxis",
    mauritius: [
      "Eine stabile Demokratie mit unabhängiger Justiz, Englisch und Französisch im Alltag, eine Einkommensteuer von höchstens 20 %, dazu eine Fair Share Contribution von 15 % oberhalb von 12 Millionen MUR, in Kraft bis zum 30. Juni 2028, Besteuerung ausländischer Einkünfte nur bei Überweisung ins Land, keine Kapitalertragsteuer und Direktflüge nach Johannesburg, Paris, London, Dubai und Singapur. Gute internationale Schulen, eine verlässliche private Gesundheitsversorgung und eine Küste, an der man leben kann.",
      "Es ist zugleich eine kleine Insel, auf der Genehmigungen ihrem eigenen Zeitplan folgen, Banken harte Fragen stellen und sich Genehmigungsregeln mit jedem Haushalt ändern. An der praktischen Seite geraten die meisten Umzüge ins Stocken. Sie ist die Seite, die wir übernehmen.",
    ],
    mauritiusLink: "Mehr über Leben und Arbeiten auf Mauritius",
    notesH: "Aktuelle Beiträge",
    notesLink: "Alle Beiträge",
    credibility: "start.mu wird von Intrasia Corporate Services Limited betrieben, beim Registrar of Companies von Mauritius als Company Secretary und Corporate Service Provider registriert, und Teil der Intrasia Group mit Präsenz auf Mauritius, in Singapur, Dubai, London und Südafrika.",
  },
  insightsPage: {
    title: "Beiträge",
    meta: "Notizen zu Aufenthalt, Gründung, Immobilien und dem Leben auf Mauritius, von start.mu.",
    lead: "Notizen zu den Genehmigungsregeln, während sie sich ändern, zur praktischen Seite der Niederlassung hier und zu den Fragen, die Mandanten am häufigsten stellen.",
    empty: "Die ersten Notizen werden vorbereitet. In der Zwischenzeit führen die Abschnitte Aufenthalt, Gründung und Immobilien die aktuellen Schwellen und den Ablauf jedes Verfahrens.",
    emptyLink: "Die Aufenthaltswege vergleichen",
    reviewed: "Zuletzt geprüft",
    categories: {
      Residency: "Aufenthalt",
      Establishment: "Gründung",
      Property: "Immobilien",
      "Living in Mauritius": "Leben auf Mauritius",
    },
  },
  aboutPage: {
    metaTitle: "Über start.mu, die Private-Client-Praxis der Intrasia Group",
    meta: "start.mu begleitet Investoren, Unternehmer und Familien bei Aufenthalt, Occupation Permits und Gesellschaftsgründung auf Mauritius. Von Anfang an klar.",
    title: "Über start.mu",
    lead: "Die Private-Client-Praxis der Intrasia Group auf Mauritius.",
    firmH: "Die Kanzlei",
    firm: [
      "start.mu ist die Private-Client-Praxis der Intrasia Group auf Mauritius, betrieben von Intrasia Corporate Services Limited. Der Name ist kurz, weil unsere Mandanten aus vielen Sprachen kommen und ein Name zählt, den sie aussprechen und tippen können. Die Kanzlei dahinter, ihre Registrierungen und ihre Menschen sind die der Gruppe.",
      "Wir helfen Privatpersonen, Familien und Unternehmen, sich auf Mauritius niederzulassen, sei es durch einen Aufenthaltsantrag, die Gründung einer Gesellschaft, den Kauf eines Zuhauses oder die Führung eines bereits laufenden Betriebs.",
      "Hinter der Praxis steht die Intrasia Group: eine lizenzierte Management Company, ein lizenzierter Vermögensverwalter, ein Bereich für Compliance und Regulierungstechnologie sowie ein Immobilienbereich, mit Büros auf Mauritius, in Singapur, Dubai, London und Südafrika. Was eine lizenzierte Management Company, eine Compliance-Prüfung, eine Einschätzung zu einer anderen Jurisdiktion oder einen Spezialisten verlangt, den wir nicht im Haus haben, bleibt innerhalb der Gruppe. Mandanten haben es mit einer Praxis zu tun und verfügen über die Ressourcen der gesamten Gruppe.",
      "Unsere Aufgabe ist es, das Verfahren klar zu machen. Wir legen die Anforderungen dar, bereiten die Unterlagen vor und koordinieren jeden Schritt, vom ersten Gespräch bis zur Genehmigung und darüber hinaus. Bevor Sie sich zu etwas verpflichten, sollten Sie wissen, was verlangt wird, was es kostet und wie lange es voraussichtlich dauert.",
      "Unsere Leistungen auf Mauritius werden über Intrasia Corporate Services Limited erbracht, die beim mauritischen Registrar of Companies als Company Secretary und Corporate Service Provider registriert ist. Wir führen den Antrag von Anfang bis Ende, einschließlich sämtlicher Kontakte mit dem Economic Development Board, dem Passport and Immigration Office und weiteren Behörden.",
      "Wo eine rechtliche, steuerliche, anlagebezogene oder regulierte Finanzberatung erforderlich ist, vermitteln wir unsere Mandanten an entsprechend qualifizierte Fachleute. Für Strukturen, die eine lizenzierte Management Company voraussetzen, arbeiten wir mit unserer Schwestergesellschaft Intrasia Management (Mauritius) Limited, die von der Financial Services Commission lizenziert ist.",
    ],
    servicesH: "Was wir tun",
    services: [
      "Anträge auf Occupation Permits der Kategorien Investor, Professional, Self-Employed und Innovator",
      "Anträge auf die Aufenthaltsgenehmigung für Retired Non-Citizens",
      "Anträge auf Aufenthaltsgenehmigungen im Zusammenhang mit zugelassenen Immobilienkäufen",
      "Anträge auf Golden Visa und Premium Visa",
      "Gesellschaftsgründung und Gewerberegistrierung",
      "Eingetragener Sitz, Company Secretary und ansässiger Direktor",
      "Anträge auf Geschäfts- und Privatkonten",
      "Immobilienerwerb in den zugelassenen Programmen, einschließlich Kauf vom Plan",
      "Laufende Gesellschaftsverwaltung, gesetzliche Pflichten und EDB-Meldungen",
      "Concierge: Schulen, Wohnen, Krankenversicherung, Fahrzeuge und Haushalt",
    ],
    hermanRole: "General Manager, Intrasia Corporate Services",
    herman: [
      "Herman Suhirman leitet die Praxis auf Mauritius. Er arbeitet mit Investoren, Unternehmern, Fachkräften und Familien an Gesellschaftsgründung, Lizenzen und aufsichtsrechtlichen Genehmigungen, an Aufenthalt und Occupation Permits sowie an grenzüberschreitenden Strukturen, und er führt das Team, das jedes Mandat zu Ende bringt.",
      "Der Ansatz ist praktisch: feststellen, was ein Weg tatsächlich verlangt, dies vor jeder Einreichung bei den Behörden bestätigen lassen und ohne vermeidbare Verzögerung von der Entscheidung zur Umsetzung kommen. Anträge, Gründungen, Kontoeröffnungen und der Verkehr mit dem Economic Development Board und dem Passport and Immigration Office werden im Haus bearbeitet, von Menschen, die diese Arbeit jede Woche tun.",
      "Seine Tätigkeit reicht über die gesamte Intrasia Group. Über Intrasia Properties wirkt er am Erwerb, der Entwicklung und der Strukturierung gewerblicher und wohnwirtschaftlicher Immobilien mit, und er arbeitet an Compliance-Technologie für Identitätsprüfungen, verstärkte Sorgfaltspflichten und die Beobachtung nachteiliger Medienberichte. Diese Bandbreite zählt hier, denn das meiste, was Mandanten zu uns bringen, liegt dort, wo Regulierung, Kapital und reale Werte zusammentreffen.",
      "Sein beruflicher Werdegang umfasst Mauritius und Singapur, und er hat an der University of Melbourne studiert.",
    ],
    leaRole: "Senior Client Executive",
    lea: [
      "Lea Permal ist bei den meisten unserer Mandate die tägliche Ansprechpartnerin. Sie bereitet Anträge auf Aufenthalts- und Occupation Permits vor und reicht sie ein, betreut Gründungen, den eingetragenen Sitz und das Company-Secretary-Wesen und führt Kontoeröffnungen sowie den Schriftwechsel mit dem Economic Development Board und dem Passport and Immigration Office.",
      "Sie ist diejenige, die weiß, wo eine Akte steht, was die Behörde verlangt hat und was noch offen ist. Die meisten Mandanten sprechen häufiger mit ihr als mit allen anderen hier, und das ist Absicht: Die Arbeit geht schneller voran, wenn eine Person das ganze Bild hat.",
    ],
    groupH: "Teil der Intrasia Group",
    groupIntro:
      "start.mu ist Teil der Intrasia Group, einer internationalen Gruppe für Unternehmens-, Management-, Investment- und Finanzdienstleistungen, mit Präsenz auf Mauritius, in Singapur, Dubai, London und Südafrika. Neben dieser Praxis umfasst die Gruppe:",
    companies: [
      { name: "Intrasia Management (Mauritius) Limited", body: "die regulierte Management Company der Gruppe auf Mauritius, für Strukturen, die eine solche voraussetzen" },
      { name: "Intrasia Wealth Limited", body: "die Vermögensverwaltungsgesellschaft der Gruppe, präsent auf Mauritius, in Dubai, Singapur und Südafrika. Sie ist von der Financial Services Commission (Mauritius) als Investment Adviser (Unrestricted) lizenziert, Lizenz-Nr. IX24200006, und von der Financial Sector Conduct Authority (Südafrika) als Category 1 Adviser, Lizenz-Nr. 54955" },
      { name: "Intrasia Intelligence Solutions Limited", body: "der Bereich der Gruppe für Compliance und Regulierungstechnologie: Sanktions- und Negativpresse-Screening, Identitätsprüfungen, verstärkte Sorgfaltspflichten und AML/CFT-Audits" },
      { name: "Intrasia Properties Ltd", href: "https://www.intrasiaproperties.com", body: "der Immobilienbereich der Gruppe, der ein eigenes gewerbliches Immobilienportfolio entwickelt und verwaltet, mit Beteiligungen auf Mauritius, in Singapur und Madagaskar sowie laufenden Büroprojekten auf Mauritius" },
    ],
    groupAfter:
      "Dieses weitere Netz erlaubt es uns, Mandanten zu begleiten, deren geschäftliche, familiäre oder Anlageinteressen über Mauritius hinausreichen. Wird zusätzliche Expertise gebraucht, bringen wir Sie mit den richtigen Spezialisten innerhalb der Gruppe oder mit unabhängigen Fachleuten zusammen, mit denen wir bereits gearbeitet haben.",
    singaporeH: "Intrasia in Singapur",
    singapore:
      "Intrasia Corporate Services Pte Ltd unterstützt Start-ups sowie kleine und mittlere Unternehmen in Singapur mit Company-Secretary-Leistungen, Buchhaltung, steuerlicher Unterstützung, Lohnabrechnung, Personalwesen und allgemeiner Unternehmensverwaltung.",
    singaporeLabel: "Singapur",
    ctaH: "Sprechen Sie mit uns",
    ctaBody: "Sagen Sie uns, was Sie erreichen möchten, und wir erklären, wie wir helfen können, was wir von Ihnen brauchen und wie es weitergeht.",
  },
  mauritiusPage: {
    title: "Mauritius in der Praxis",
    meta: "Leben und Wirtschaften auf Mauritius: Steuern, Recht, Sprachen, Schulen, Gesundheitsversorgung, Banken, Flugverbindungen und die praktische Seite eines Umzugs auf die Insel.",
    lead: "Eine stabile Demokratie im Indischen Ozean mit einem hybriden Rechtssystem, Englisch und Französisch im Alltag, einem wettbewerbsfähigen Steuerrecht und einem Leben, das sich wirklich an der Küste abspielt. Zugleich ist es eine kleine Insel, auf der Verwaltungsvorgänge Zeit und Geduld erfordern können. Beide Wirklichkeiten zählen.",
    frameworkH: "Der Rahmen",
    caption: "Mauritius: steuerlicher, rechtlicher und praktischer Rahmen",
    disclaimer: "Steuersätze und Abkommenslagen ändern sich. Wir sind keine Steuerberater und vermitteln einen mauritischen Steuerspezialisten, wenn es darauf ankommt.",
    livingH: "Hier leben",
    living: [
      "Der Norden ist die Gegend, die viele zuziehende Familien zuerst ansehen. Grand Baie und Pereybère bieten Strände, Restaurants und die Bequemlichkeit des Alltags, und die Golf- und Strandanlagen an dieser Küste gehören zu den bekanntesten der Insel. Weiter im Landesinneren, um Piton, sprechen bewachte Anlagen Familien an, die eine ruhigere, grünere Umgebung mit guter Anbindung an Schulen und Autobahn suchen. Der Westen, von Tamarin bis Black River, ist vom Leben im Freien geprägt, die Berge im Rücken, die Lagune davor: Surfen, Wandern und Segeln neben etablierten Familienvierteln und der einzigen echten Marina-Wohnanlage der Insel in Black River. Die Bautätigkeit hat zugenommen; die Region ist eher entspannt im Charakter als durchgehend ruhig.",
      "Das Zentrum, insbesondere Moka und das nahe Ebène, ist die praktische Alternative zum Leben an der Küste. Mokas Wohnviertel und die Smart-City-Projekte bringen Familien in die Nähe mehrerer führender Schulen, der wichtigsten Geschäftsviertel, der Gesundheitsversorgung und der Einkaufsmöglichkeiten. Der Preis dafür ist die Entfernung zum Strand; die Vorteile sind Bequemlichkeit, ein kühleres Klima im Hochland und kürzere Alltagswege.",
      "Die internationalen Schulen folgen dem englischen, dem französischen oder dem International-Baccalaureate-System. Die private Gesundheitsversorgung ist gut und preislich vernünftig; komplexe Fälle werden nach Südafrika, La Réunion oder Europa überwiesen, weshalb eine im Ausland gültige Versicherung zählt. Hauspersonal ist erschwinglich und weit verbreitet. Es herrscht Linksverkehr, und außerhalb der Städte ist ein Auto notwendig.",
    ],
    businessH: "Hier wirtschaften",
    business: [
      "Mauritius ist gut reguliert, und das zeigt sich im Papierkram. Banken wenden bei Nichtansässigen verstärkte Sorgfaltspflichten an. Das Economic Development Board prüft, ob Genehmigungsinhaber ihre Bedingungen erfüllen, und diese Kontrolle hat Zähne. Der Registrar of Companies, die Mauritius Revenue Authority und die Financial Services Commission erwarten jeweils fristgerechte Meldungen.",
      "Nichts davon ist schwierig, wenn es von Anfang an in die Hand genommen wird. Die meisten Schwierigkeiten, die wir sehen, stammen aus flüchtig vorbereiteten Akten, aus nicht zu Ende gedachten Strukturen oder aus Schwellen, die niemand nachverfolgt hat. An der praktischen Seite geraten Umzüge ins Stocken, und diese Seite übernehmen wir.",
    ],
    facts: [
      { label: "Einkommensteuer", value: "Progressive Sätze bis 20 % seit der Reform von 2023. Auf leviable income über 12 Millionen MUR kommt eine Fair Share Contribution von 15 %, für die Steuerjahre vom 1. Juli 2025 bis 30. Juni 2028. Leviable income ergänzt das zu versteuernde Einkommen um Dividenden ansässiger Gesellschaften: mauritische Dividenden, die sonst steuerfrei sind, zählen also auf die Schwelle. Ausländische Einkünfte von Ansässigen werden nach der Remittance-Basis besteuert" },
      { label: "Körperschaftsteuer", value: "15 %, mit Teilbefreiungen für bestimmte Einkunftsarten. Keine Kapitalertragsteuer. Keine Erbschaftsteuer" },
      { label: "Steuerliche Ansässigkeit", value: "183 Tage in einem Steuerjahr oder 270 Tage über drei aufeinanderfolgende Jahre" },
      { label: "Doppelbesteuerungsabkommen", value: "Ein Netz von über 40 in Kraft befindlichen Abkommen, unter anderem mit Südafrika, Frankreich, dem Vereinigten Königreich, Deutschland, Indien und China" },
      { label: "Rechtssystem", value: "Eine Mischung aus französischem Zivilrecht und englischem Common Law, mit letzter Instanz vor dem Judicial Committee of the Privy Council" },
      { label: "Sprachen", value: "Englisch ist die Sprache von Verwaltung und Recht. Französisch wird weithin gesprochen. Mauritisches Kreol ist die Alltagssprache" },
      { label: "Währung", value: "Mauritische Rupie, frei konvertierbar, ohne Devisenkontrollen" },
      { label: "Zeitzone", value: "GMT +4, was sich mit Afrika, Europa, dem Golf und Asien innerhalb eines Arbeitstags überschneidet" },
      { label: "Flüge", value: "Direktverbindungen nach Johannesburg, Kapstadt, Durban, Paris, London, Dubai, Mumbai, Singapur, Perth und La Réunion" },
    ],
  },
  conciergePage: {
    title: "Concierge",
    meta: "Was Genehmigung und Gesellschaft nicht abdecken: Schulen, ein Zuhause, Krankenversicherung, Bankkonten, Fahrzeuge, Hauspersonal und ein Buchhalter vor Ort, vermittelt und übergeben von start.mu, der Private-Client-Praxis der Intrasia Group.",
    metaTitle: "Concierge und Umzug",
    lead: "Was Genehmigung und Gesellschaft nicht abdecken. Vermittelt, eingerichtet und still übergeben, damit der Umzug in der Praxis nicht Ihr Projekt wird.",
    requestH: "Auf Anfrage",
    request: [
      "Der Concierge-Service ist nicht standardmäßig enthalten. Er wird eingerichtet, wenn eine Familie darum bittet, und was wir übernehmen, wird mit Ihnen vereinbart und im schriftlichen Angebot neben der Genehmigung und der Gründung festgehalten.",
      "Fragen Sie früh. Schulen nehmen nach eigenen Fristen auf, und ein Mietvertrag, ein Bankkonto oder eine Krankenversicherung lassen sich vor der Ankunft leichter regeln als danach. Je früher wir wissen, was Sie brauchen, desto mehr steht am Tag der Landung bereit.",
      "Wir vermitteln und koordinieren. Die Schulen, die Versicherer, die Vermieter, der Buchhalter und das Hauspersonal schließen unmittelbar mit der Familie ab, und wir treten zurück, sobald jede Vereinbarung läuft.",
    ],
    areas: [
      { title: "Schulen", body: "Vermittlung an die internationalen und privaten Schulen, die zur Familie passen, Besichtigungen organisiert, das Aufnahmeverfahren begleitet und der Zeitplan auf die Genehmigung abgestimmt, damit die Plätze vor der Ankunft gesichert sind." },
      { title: "Ein Zuhause", body: "Miete oder Kauf, in den Gegenden, die zum Leben der Familie passen: nahe den Schulen, nahe dem Büro oder an der Küste. Wir treffen eine Vorauswahl, vereinbaren Besichtigungen, prüfen Mietverträge und handeln beim Kauf für den Erwerber durch das gesamte Programmverfahren." },
      { title: "Krankenversicherung", body: "Eine private Krankenversicherung, die auf Mauritius und im Ausland gilt, mit Vermittlung der Kliniken und Fachärzte vor Ort. Die für die Genehmigung erforderlichen Untersuchungen werden bei den zugelassenen Ärzten organisiert." },
      { title: "Bank und Geld", body: "Privatkonten eröffnet, Karten ausgestellt, Überweisungen aus dem Ausland so geplant, dass die Bedingungen der Genehmigung fristgerecht erfüllt sind, und ein Buchhalter vor Ort für die persönliche Steuererklärung vermittelt." },
      { title: "Fahrzeuge und Versorgung", body: "Ein Wagen gesucht, gekauft oder geleast, zugelassen und versichert. Strom, Wasser, Internet und Mobilfunk auf den Namen der Familie eingerichtet, bevor die erste Nacht im Haus beginnt." },
      { title: "Haushalt", body: "Hauspersonal vermittelt und ordnungsgemäß angestellt, mit Verträgen und Anmeldung zur Sozialversicherung. Ein Gärtner, eine Poolfirma, ein Handwerker: die Menschen, die ein Haus am Laufen halten." },
    ],
  },
  contactPage: {
    title: "Beratungsgespräch vereinbaren",
    meta: "Wenden Sie sich an start.mu auf Mauritius, um ein erstes Gespräch über Aufenthalt, Gesellschaftsgründung, Immobilienerwerb oder Umzug zu vereinbaren.",
    lead: "Das erste Gespräch findet nach Vereinbarung statt und dauert eine Stunde, persönlich auf Mauritius oder per Videokonferenz. Sagen Sie uns kurz, was Sie vorhaben, und wir schlagen einen Termin vor.",
    directlyH: "Direkt",
    expectH: "Was Sie erwartet",
    expect:
      "Wir antworten innerhalb eines Werktags. Nach dem Gespräch erhalten Sie ein schriftliches Angebot mit dem empfohlenen Weg, dem Leistungsumfang, den Honoraren und dem Zeitplan. Es ist unverbindlich und kostenfrei.",
  },
  form: {
    name: "Name",
    email: "E-Mail",
    interest: "Worüber Sie sprechen möchten",
    message: "Nachricht",
    placeholder: "Sagen Sie uns, was Sie vorhaben und ungefähr wann. Ein paar Zeilen genügen.",
    send: "Nachricht senden",
    sending: "Wird gesendet",
    sentH: "Nachricht erhalten",
    sentBody: "Wir antworten innerhalb eines Werktags und schlagen einen Gesprächstermin vor.",
    privacyBefore: "Wir verwenden, was Sie hier senden, ausschließlich zur Beantwortung Ihrer Anfrage. Unsere ",
    privacyLink: "Datenschutzerklärung",
    privacyAfter: " erläutert, wie lange wir es aufbewahren und was Sie von uns verlangen können.",
    failed: "Die Nachricht konnte nicht gesendet werden.",
    interests: [
      "Aufenthaltsgenehmigung",
      "Gesellschaftsgründung",
      "Immobilienerwerb",
      "Golden Visa",
      "Concierge und Umzug",
      "Etwas anderes",
    ],
  },
  establishmentPage: {
    title: "Gründung",
    lead: "Eine gegründete und verwaltete Gesellschaft, ein eröffnetes Bankkonto, ein eingetragener Sitz und ein Company Secretary, von uns geführt. Die Struktur, die Ihre Genehmigung oder Ihr Geschäft verlangt, vom ersten Tag an einsatzbereit und danach in gutem Stand gehalten.",
    whichH: "Welche Struktur passt",
    adminH: "Verwaltung",
    adminLead: "Die Leistungen, die eine Gesellschaft und eine Genehmigung Jahr für Jahr in gutem Stand halten.",
  },
  propertyPage: {
    title: "Immobilien",
    lead: "Ein Nicht-Staatsbürger darf auf Mauritius Wohnimmobilien innerhalb der vom Economic Development Board zugelassenen Programme erwerben und ab 375.000 USD hier leben, solange die Immobilie gehalten wird. Die Programme unterscheiden sich in dem, was sie bieten, und in dem, was vor dem Kauf zu prüfen ist. Wir handeln allein für den Käufer: Wir sind für keinen Bauträger als Makler tätig und nehmen von Verkäufern keine Provision.",
    comparedH: "Die Programme im Vergleich",
    sequenceH: "So läuft ein Erwerb ab",
    sequenceLead: "Der Ablauf ist in allen Programmen derselbe. Beim Kauf vom Plan kommen Ratenzahlungen und eine Fertigstellungsgarantie hinzu, die wir gesondert behandeln.",
    vefaLink: "Kauf vom Plan und VEFA",
    actH: "Für wen wir handeln",
    act: [
      "Wir handeln für den Käufer. Wir sind für keinen Bauträger als Makler tätig und nehmen von Verkäufern keine Provision. Unser Honorar wird mit dem Käufer im schriftlichen Angebot vereinbart, und unsere Einschätzung zu einem Projekt, einer Garantie oder einem Zahlungsplan erfolgt allein mit Blick auf die Position des Käufers.",
      "Wenn der Käufer die Immobilie lieber über eine mauritische Gesellschaft und einen Trust hält, richten wir die Struktur parallel zur Reservierung ein, damit sich die Urkunde nicht verzögert.",
    ],
    sequence: [
      { title: "Reservierung", body: "Eine Reservierungsvereinbarung mit dem Bauträger oder Verkäufer, wobei die Anzahlung beim Notar hinterlegt wird." },
      { title: "Genehmigung des EDB", body: "Der Antrag des Käufers beim Economic Development Board auf Erwerbsgenehmigung, mit Identität, Mittelherkunft und, soweit einschlägig, der Struktur, über die die Immobilie gehalten wird." },
      { title: "Urkunde", body: "Die notarielle Kaufurkunde, oder die VEFA-Urkunde beim Kauf vom Plan, unterzeichnet vor einem Notar. Die Registrierungsgebühr von 5 % trägt der Käufer." },
      { title: "Eintragung und Genehmigung", body: "Die Eintragung der Urkunde und, bei Erwerben ab 375.000 USD, der Antrag auf die Aufenthaltsgenehmigung über das EDB." },
    ],
  },
  residencyPage: {
    title: "Aufenthalt",
    lead: "Acht Wege nach Mauritius, jeder mit eigener Schwelle, Dauer und eigenen Bedingungen. Welcher passt, hängt davon ab, was Sie vorhaben: ein Unternehmen führen, arbeiten, den Ruhestand verbringen, investieren oder zunächst eine Weile hier leben.",
    finder: "Unsicher? Vier Fragen",
    compareH: "Alle Wege im Vergleich",
    chooseH: "Die Wahl zwischen ihnen",
    choose: [
      "Die meisten kommen mit einem Weg im Kopf und verlassen das erste Gespräch mit einem anderen. Wer glaubte, eine Immobilie kaufen zu müssen, entdeckt die Genehmigung für Ruheständler. Der Berater, der eine Gesellschaft gründen wollte, findet die Genehmigung für Selbständige einfacher. Der Gründer, der keine 100.000 USD aufbringen kann, erfährt, dass der Weg für innovative Start-ups keine Mindestinvestition verlangt.",
      "Die entscheidenden Fragen sind praktischer Natur. Führen Sie hier ein Unternehmen oder arbeiten Sie für eines? Sind Sie über 50? Möchten Sie ohnehin ein Haus besitzen? Wie viel Kapital sind Sie bereit einzusetzen, und wie schnell müssen Sie hier sein? Unsere Aufgabe ist es, diese Fragen zu stellen und klar zu sagen, welcher Weg passt.",
    ],
    alsoH: "Ebenfalls in diesem Abschnitt",
  },
  untranslated: "Diese Seite ist derzeit auf Englisch verfügbar. Die deutsche Fassung folgt.",
};

export const ui: Record<Locale, Ui> = { en, fr, de };
