import type { Insight } from "@/lib/cms";

/** Deutsche Fassungen der Startbeiträge. Zahlenangaben sind unverändert übernommen. */
export const insightsDe: Record<string, Partial<Insight>> = {
  "cost-of-living-mauritius-family": {
    title: "Lebenshaltungskosten auf Mauritius: ein realistisches Budget für Familien",
    summary:
      "Mauritius ist nicht die billige Insel, die die Prospekte nahelegen. Wohin das Geld bei einer Familie geht, die 2026 ankommt, mit den wichtigsten Preisspannen und den Faktoren, die sie beeinflussen.",
    body: `
<p>Das häufigste Missverständnis, das wir richtigstellen, ist die Annahme, Mauritius sei günstig. Für eine Familie, die eine europäische oder südafrikanische Lebensweise fortführt, mit einem Haus an der Küste, importierten Lebensmitteln, internationaler Schule und privater Medizin, ist sie es nicht. Die Zahlen unten sind Richtwerte aus 2026 und sollen die Entscheidung einordnen, nicht ein ordentliches Budget ersetzen. Sie bewegen sich mit dem Wechselkurs, der Gegend und den Entscheidungen einer Familie.</p>
<p><strong>Wohnen.</strong> Die Miete ist der größte und veränderlichste Posten. Eine moderne Zweizimmerwohnung im Norden um Grand Baie liegt zwischen 35.000 und 70.000 MUR im Monat. Ein Familienhaus mit drei oder mehr Schlafzimmern und Pool im Norden oder Westen kostet rund 2.000 bis 5.000 USD im Monat, und die großen Villen in den Anlagen liegen deutlich darüber. Zehn Minuten landeinwärts, in Pamplemousses oder Triolet, bekommt man für dasselbe Geld erheblich mehr. Mietobjekte sind fast immer möbliert, und eine Kaution von ein bis zwei Monatsmieten zuzüglich Maklerhonorar wird vor der Ankunft gezahlt.</p>
<p><strong>Schule.</strong> Der zweite Posten für eine Familie mit Kindern und derjenige, der am häufigsten überrascht. Die Jahresgebühren an den englischsprachigen internationalen Schulen reichen von rund 180.000 MUR in den ersten Jahren bis über 600.000 MUR am oberen Ende der Sekundarstufe, je nach Schule. Eine Familie mit zwei Kindern in der Sekundarstufe sollte 700.000 bis 1.200.000 MUR im Jahr allein an Schulgeld einplanen, vor Aufnahmegebühr, Schulbus und Nebenkosten. Zur Schulwahl gibt es einen eigenen Beitrag.</p>
<p><strong>Gesundheit.</strong> Öffentliche Krankenhäuser sind für Ansässige kostenfrei, die meisten Familien nutzen jedoch die privaten Kliniken und zahlen pro Leistung. Eine private Hausarztkonsultation liegt zwischen 1.000 und 3.000 MUR. Die eigentlichen Kosten stecken in der Versicherung: ein einfacher lokaler Tarif ab etwa 2.000 bis 4.000 MUR im Monat pro Person, und ein internationaler Tarif mit Evakuierungsschutz ab etwa 200 bis 500 USD im Monat. Am Evakuierungsbaustein sollte man nicht sparen.</p>
<p><strong>Einkauf und Nebenkosten.</strong> Einheimische Erzeugnisse, Fisch und Reis sind günstig; importierte Waren tragen Zölle und kosten spürbar mehr als zu Hause. Eine allein lebende Person, die selbst kocht, gibt etwa 10.000 bis 15.000 MUR im Monat für Lebensmittel aus; eine Familie das Zwei- bis Dreifache, mehr, wenn der Wagen voller Importmarken ist. Strom, Wasser und Internet kosten einen Haushalt einige tausend Rupien im Monat, im Sommer deutlich mehr, wenn die Klimaanlage nachts durchläuft.</p>
<p><strong>Verkehr.</strong> Außerhalb der Städte ist ein Auto notwendig, und Autos sind wegen der Einfuhrzölle teuer. Planen Sie diesen Kauf und den Kraftstoff von Anfang an ein. Öffentlichen Verkehr gibt es, doch damit bringt eine zuziehende Familie ihre Kinder nicht zur Schule.</p>
<p><strong>Was man dafür bekommt.</strong> Eine persönliche Besteuerung mit einem Höchstsatz von 20 % bis 12 Millionen MUR zu versteuerndem Einkommen und 35 % darüber seit dem 1. Juli 2026, eine Remittance-Basis für ausländische Einkünfte, keine Steuer auf Kapitalgewinne, keine Vermögensteuer, keine Erbschaftsteuer. Sicherheit. Haushaltshilfe zu nach europäischen Maßstäben niedrigen Löhnen. Einen Winter, der nicht stattfindet. Die meisten Familien, die ehrlich rechnen, kommen auf eine Summe, die einer mittelgroßen europäischen Stadt entspricht, und stellen fest, dass sie für das Leben zahlen und nicht für einen Rabatt.</p>
`,
    faqs: [
      { q: "Ist Kaufen günstiger als Mieten?", a: "Auf lange Sicht oft, und ein Erwerb ab 375.000 USD in einem zugelassenen Programm begründet einen Anspruch auf eine Aufenthaltsgenehmigung. Wir raten jedoch jeder Familie, im ersten Jahr zu mieten. Wo man zu wohnen glauben möchte und wo man tatsächlich wohnen möchte, sind häufig verschiedene Orte." },
      { q: "Wie viel sollten wir für den Umzug selbst einplanen?", a: "Zwei Erkundungsreisen, Transport oder Neuanschaffung der Möbel, Kautionen für Haus und Schule, das Auto sowie die Honorare für Genehmigung und Gesellschaft. Zusammen übersteigen diese Posten meist, was Familien erwarten, und sie fallen in den ersten drei Monaten an." },
      { q: "Unterscheiden sich die Kosten stark zwischen Norden, Westen und Zentrum?", a: "Ja. Die Nordküste ist beim Wohnen am teuersten, der Westen folgt dicht dahinter, und das Zentrum um Moka ist bei gleichem Haus deutlich günstiger und liegt zugleich näher an Schulen und Büros. Dörfer im Landesinneren, fünf bis zehn Minuten von der Küste, sind nochmals günstiger." },
    ],
  },

  "international-schools-mauritius-choosing": {
    title: "Eine Schule auf Mauritius wählen: Lehrpläne, Gegenden, Gebühren und Zeitplanung",
    summary:
      "Die Schule entscheidet, wo Sie wohnen, nicht umgekehrt. Die englischen, französischen und IB-Angebote der Insel, was sie kosten, und warum die Anmeldung vor dem Genehmigungsantrag beginnen sollte.",
    body: `
<p>Jeder zuziehenden Familie sagen wir beim ersten Termin dasselbe: Wählen Sie die Schule vor dem Haus. Die Insel ist klein, der Verkehr ist es nicht, und die tägliche Fahrt von der falschen Küste zur richtigen Schule ist der häufigste einzelne Grund, warum Familien im ersten Jahr nach der Ankunft nochmals umziehen.</p>
<p><strong>Drei Systeme.</strong> Englischsprachige Schulen folgen dem britischen Lehrplan bis zu Cambridge IGCSE und A-Levels, mehrere bieten daneben das International Baccalaureate an; französische Schulen folgen dem französischen Lehrplan bis zum baccalauréat, homologiert vom französischen Ministerium, und eine bietet in den letzten Jahren das IB-Diplom an; hinzu kommen die staatlichen mauritischen Schulen, kostenfrei und zweisprachig, von zuziehenden Familien aber selten gewählt. Für den Hochschulzugang in Großbritannien oder Südafrika werden A-Levels und IB gleichermaßen anerkannt. Für eine Familie, die möglicherweise erneut umzieht, ist der bereits besuchte Lehrplan meist derjenige, bei dem sie bleiben sollte.</p>
<p><strong>Wo die Schulen liegen.</strong> Im Norden befindet sich die größte und etablierteste englischsprachige Schule in Mapou, die Kinder von 18 Monaten bis 18 Jahren aufnimmt, dazu eine angesehene Grundschule im selben Ort und eine französische Schule. Der Westen hat eine englischsprachige Sekundarschule bei Flic en Flac und ein wachsendes Grund- und Sekundarangebot um Tamarin. Das zentrale Plateau um Moka vereint die zweite der beiden großen englischsprachigen Sekundarschulen, eine weitere IB-Schule sowie das wichtigste französische Lycée und die zugehörige Grundschule. Osten und Süden bieten weit weniger Auswahl, und Familien dort nehmen lange Fahrwege in Kauf.</p>
<p><strong>Gebühren.</strong> Die englischsprachigen Schulen rechnen nach Jahrgang ab, und der Sprung zur Sekundarstufe ist deutlich. Die veröffentlichten Gebühren für 2025-26 an der größten Schule reichen von rund 161.700 MUR im Jahr in den ersten Jahren bis 608.300 MUR in den letzten Jahren. Die Sekundarschule in Moka verlangt etwa 32.000 bis 35.000 MUR im Monat über elf Monate. Aufnahmegebühren von 10.000 bis 30.000 MUR und ein Schulbus mit 18.000 bis 40.000 MUR im Jahr kommen hinzu, Geschwisterrabatte von 7,5 % bis 15 % sind üblich. Die französischen Schulen sind günstiger. Die Gebühren werden jährlich überprüft; bestätigen Sie die aktuellen Zahlen daher bei der Schule, bevor Sie budgetieren.</p>
<p><strong>Zeitplanung.</strong> Die guten Schulen führen Wartelisten in genau den Jahrgängen, in die Familien am häufigsten kommen, besonders in den ersten Grundschuljahren und im ersten Jahr der Sekundarstufe. Sechs bis zwölf Monate Vorlauf sind normal, mehr ist sicherer. Das heißt: Die Schulanmeldung beginnt vor dem Genehmigungsantrag, nicht danach, und die Anmeldegebühr ist oft das erste Geld, das für den Umzug ausgegeben wird.</p>
<p><strong>Was wir tun.</strong> Der Familie die zwei oder drei Schulen vorstellen, die zum Alter der Kinder und zum bisherigen Lehrplan passen, Besichtigungen während einer Erkundungsreise organisieren, den Schriftwechsel zur Aufnahme führen und den Zusagetermin auf den Zeitplan der Genehmigung abstimmen, damit der Platz gehalten wird, bis die Familie ihn annehmen kann.</p>
`,
    faqs: [
      { q: "Brauchen unsere Kinder Französisch?", a: "Nicht für die englischsprachigen Schulen, die auf Englisch unterrichten und Französisch als Fach anbieten. Die Schulen mit französischem Lehrplan verlangen Französisch von einem frühen Zeitpunkt an. Die meisten Kinder eignen sich ohnehin rasch umgangssprachliches Französisch und Kreol an." },
      { q: "Können wir vor der Entscheidung besichtigen?", a: "Ja, und Sie sollten es tun. Eine Erkundungsreise während der Schulzeit, mit Schulbesuchen und dem Schulweg zur Hauptverkehrszeit gefahren, ist die beste Investition, die eine Familie vor dem Umzug tätigt." },
      { q: "Gibt es Internate?", a: "Nur begrenzt. Mauritius ist eine Insel der Tagesschulen. Familien an der Ost- oder Südküste greifen gelegentlich auf Wocheninternate zurück, die meisten wählen jedoch eine Wohnung in Schulnähe." },
    ],
  },

  "healthcare-mauritius-what-to-arrange": {
    title: "Gesundheitsversorgung auf Mauritius: was es gibt, was nicht, und was vor der Ankunft zu regeln ist",
    summary:
      "Gute Privatkliniken, ein kostenfreies öffentliches System, das die meisten Ansässigen meiden, und eine kleine Zahl von Erkrankungen, die im Ausland behandelt werden. Warum der Evakuierungsschutz die eine Klausel ist, auf die es ankommt.",
    body: `
<p>Mauritius hat ein zweistufiges System. Die öffentlichen Krankenhäuser sind für Ansässige kostenfrei, tragen den größten Teil der Versorgung der Insel und sind überlastet. Die Privatkliniken sind der Ort, an den zuziehende Familien gehen, und sie sind gut: Ärzte, ausgebildet in Frankreich, im Vereinigten Königreich, in Indien und Südafrika, moderne Ausstattung, kurze Wartezeiten, Englisch und Französisch durchgängig.</p>
<p><strong>Die Kliniken, die man kennen sollte.</strong> Die beiden privaten Vollversorgungshäuser liegen im Zentrum der Insel: das Wellkin Hospital der C-Care-Gruppe in Moka, das größte und modernste mit Intensivstation und 24-Stunden-Notaufnahme, und die Clinique Darné in Floréal, lange etabliert, mit Geburtshilfe und Intensivmedizin. Im Norden gibt es Privatkliniken in Grand Baie und entlang der Küstenstraße sowie ein Netz zugelassener Labore für die von der Genehmigung verlangten Untersuchungen. Von Tamarin oder Grand Baie sind die Häuser in Moka ohne Verkehr etwa zwanzig bis dreißig Minuten entfernt.</p>
<p><strong>Was im Ausland behandelt wird.</strong> Die Insel ist klein, und manche Fachgebiete haben hier nicht das Volumen, um zu bestehen. Fortgeschrittene Onkologie, komplexe Herzchirurgie und große Neurochirurgie werden regelmäßig nach Südafrika, La Réunion oder Frankreich überwiesen. Das ist kein Versagen des Systems, sondern Folge einer Bevölkerung von 1,3 Millionen. Es hat aber eine unmittelbare Konsequenz für eine zuziehende Familie: Die Krankenversicherung muss den Krankentransport und die Behandlung im Ausland einschließen, und genau diese Klausel ist vor der Unterschrift zu lesen.</p>
<p><strong>Versicherung.</strong> Zwei Möglichkeiten. Lokale Versicherer bieten Tarife ab etwa 2.000 bis 4.000 MUR im Monat pro Person für private Konsultationen, stationäre Behandlung und Medikamente auf Mauritius, meist ohne Evakuierung. Internationale Versicherer bieten Tarife ab etwa 200 bis 500 USD im Monat pro Person mit weltweitem Schutz einschließlich Evakuierung. Viele Familien kombinieren einen lokalen Tarif für den Alltag mit internationalem Schutz für den ernsten Fall. Prüfen Sie, wie der Vertrag Vorerkrankungen behandelt, ob Familienangehörige über einen Arbeitgebertarif mitversichert sind, und ob die Klinik, die Sie nutzen würden, mit dem Versicherer direkt abrechnet.</p>
<p><strong>Alltägliche Gesundheit.</strong> Apotheken sind gut sortiert und viele Medikamente sind rezeptfrei zu vernünftigen Preisen erhältlich; die Verfügbarkeit bestimmter Markenpräparate sollte vor dem Umzug geprüft werden. Das Leitungswasser ist aufbereitet, die meisten Haushalte filtern es dennoch. Dengue und Chikungunya zirkulieren in den Sommermonaten, und die Mücke ist das einzige Tier, das man ernst nehmen muss; Malaria ist praktisch nicht vorhanden. Die Zyklonsaison läuft von November bis in den April, die förmliche Warnperiode reicht bis Mitte Mai, und die Kliniken bleiben durchgehend geöffnet.</p>
<p><strong>Was wir organisieren.</strong> Die von der Genehmigung verlangte ärztliche Untersuchung in einer zugelassenen Klinik, zeitlich auf den Antrag abgestimmt. Die Vermittlung eines Hausarztes, eines Kinderarztes und eines Zahnarztes in der Nähe des künftigen Wohnorts. Und das Versicherungsgespräch vor der Ankunft statt danach, weil sich die Evakuierungsklausel auf dem Papier leichter richtig regeln lässt als im Notfall.</p>
`,
    faqs: [
      { q: "Ist das öffentliche System im Notfall nutzbar?", a: "Bei akuten Verletzungen ja: Die öffentlichen Notaufnahmen stabilisieren gut. Das übliche Muster ist die Stabilisierung im nächstgelegenen Krankenhaus und die Verlegung in eine Privatklinik zur weiteren Behandlung, weshalb die Nummer des Versicherers im Telefon stehen sollte." },
      { q: "Können wir unsere bestehende internationale Police behalten?", a: "Häufig ja, sofern sie Mauritius abdeckt und die Evakuierung einschließt. Prüfen Sie, ob der Versicherer Mauritius als Ihr Wohnsitzland und nicht als Reiseziel behandelt, denn das ändert die Bedingungen." },
      { q: "Sind die ärztlichen Untersuchungen für die Genehmigung aufwendig?", a: "Nein. Eine Reihe üblicher Blutuntersuchungen, eine Röntgenaufnahme des Brustkorbs und eine Bescheinigung eines zugelassenen Arztes auf Mauritius. Drei der Untersuchungen müssen vor Ort erfolgen; die übrigen können vor der Reise gemacht werden. Wir vereinbaren die Termine." },
    ],
  },

  "where-to-live-mauritius-north-west-centre": {
    title: "Wo auf Mauritius leben? Norden, Westen oder Zentrum",
    summary:
      "Drei Regionen nehmen nahezu jede zuziehende Familie auf. Wie es sich in jeder lebt, wer sie wählt, und der Arbeitsweg, der zwischen ihnen entscheidet.",
    body: `
<p>Mauritius misst von Norden nach Süden 65 Kilometer, und dennoch prägt der Wohnort das Jahr einer Familie stärker als in den meisten größeren Ländern. Der Grund ist das Straßennetz: eine einzige Autobahnachse durch Port Louis und Küstenstraßen, die sich zur Schulzeit füllen. Die drei folgenden Regionen nehmen fast jede Familie auf, die wir begleiten, und die Wahl zwischen ihnen entscheiden meist Schule und Büro, nicht der Strand.</p>
<p><strong>Der Norden.</strong> Grand Baie und die umliegende Küste, von Trou aux Biches über Pereybère bis Cap Malheureux, hat die größte Konzentration ausländischer Ansässiger auf der Insel. Die Gründe sind praktisch: die größte internationale Schule in Mapou, eine französische Schule, zwei Privatkliniken, der Yachthafen, Supermärkte mit importierten Sortimenten, Restaurants und Geschäfte auf einer Achse und eine hohe Dichte an Projekten der zugelassenen Programme, von denen das Mont Choisy Golf &amp; Beach Estate das bekannteste ist. Der Preis dafür sind die höchsten Wohnkosten der Insel und der Verkehr, der mit der Bevölkerung gewachsen ist. Familien, die alles zu Fuß erreichen wollen und die zu Hause oder im Norden arbeiten, wählen ihn. Zehn Minuten landeinwärts bieten Pamplemousses und Triolet dieselben Schulen zu niedrigeren Mieten, und die bewachten Anlagen um Piton, darunter das Domaine de Bon Espoir, passen zu Familien, die eine grünere Umgebung mit der Autobahn in der Nähe suchen.</p>
<p><strong>Der Westen.</strong> Tamarin, Black River und Flic en Flac, die Berge im Rücken, die Lagune davor. Trockener und wärmer als der Norden und geschützt vor den Passatwinden, wobei die Bautätigkeit an dieser Küste zugenommen hat: eher entspannt im Charakter als durchgehend ruhig. La Balise Marina in Black River ist die einzige echte Marina-Adresse der Insel, bei der der Liegeplatz am Ende des Gartens liegt. mit Surfen, Kitesurfen und Wandern vor der Tür und einer eng verbundenen Gemeinschaft langjähriger Ansässiger. Es gibt eine englischsprachige Sekundarschule bei Flic en Flac und ein wachsendes Schulangebot in Tamarin, und Port Louis liegt näher als von Grand Baie aus. Die Sommer sind heiß, und die Fahrt nach Norden zu den Schulen in Mapou dauert an einem guten Tag fünfundzwanzig Minuten. Familien, die das Draußen und ein ruhigeres Tempo suchen, wählen ihn; Ruheständler ebenso.</p>
<p><strong>Das Zentrum.</strong> Moka und das umliegende Plateau, mit dem Bürostandort Ebene, den beiden wichtigsten Privatkrankenhäusern, der zweiten großen englischsprachigen Sekundarschule, einer IB-Schule und dem französischen Lycée, alle wenige Minuten voneinander entfernt. Die Smart-City-Projekte haben daraus einen Wohnstandort gemacht statt eines Orts, zu dem man pendelt. Es ist kühler und feuchter als an der Küste, und das Meer liegt in jede Richtung zwanzig bis dreißig Minuten entfernt. Die Mieten liegen bei gleichem Haus deutlich unter denen der Küste. Familien mit Kindern im Sekundarschulalter und einem Elternteil, der in Ebene oder Port Louis arbeitet, wählen es zunehmend, und der Arbeitsweg ist der Grund.</p>
<p><strong>Osten und Süden.</strong> Schön, weniger erschlossen und günstiger, mit einer Handvoll großer Resortanlagen. Wenige Schulen und lange Fahrten zu den vorhandenen. Gewählt von Familien ohne schulpflichtige Kinder und von Käufern in einer bestimmten Anlage.</p>
<p>Wir nennen diese Anlagen, weil Mandanten sie beim Namen ansprechen, nicht weil wir für jemanden handeln, der dort verkauft. Wir handeln allein für den Käufer, nehmen von Bauträgern und Verkäufern keine Provision, und jede Einschätzung zu einem Projekt geben wir allein mit Blick auf die Position des Käufers.</p>
<p><strong>Wie man entscheidet.</strong> Finden Sie die Schule. Finden Sie das Büro, falls es eines gibt. Fahren Sie an einem Schultag um acht Uhr morgens zwischen ihnen und den infrage kommenden Häusern hin und her. Dann entscheiden Sie. Wir richten Erkundungsreisen genau um diese Übung herum ein, mit Besichtigungen in zwei Regionen und dem Schulweg zur maßgeblichen Uhrzeit.</p>
`,
    faqs: [
      { q: "Ist Grand Baie überteuert?", a: "Für das, was man in manchen Ecken bekommt, ja, und langjährige Ansässige werden das sagen. Man bezahlt die Bequemlichkeit. Wenn diese Bequemlichkeit für Ihre Familie zählt, ist sie es wert; wenn nicht, schauen Sie landeinwärts oder in den Westen." },
      { q: "Welche Region hat das beste Wetter?", a: "Der Westen, trockener und geschützter. Der Norden ist warm und windiger. Das Zentrum ist kühler und feuchter, was manche Familien im Sommer schätzen und andere nicht." },
      { q: "Lohnen sich die bewachten Anlagen?", a: "Für Sicherheit, Gemeinschaft und Dienstleistungen häufig ja, und für einen Nicht-Staatsbürger, der Immobilien kauft, sind sie oft die einzige Möglichkeit. Zur Miete kann ein Haus im Dorf mehr Platz fürs Geld bieten, um den Preis einiger Bequemlichkeit." },
    ],
  },

  "bringing-pets-to-mauritius": {
    title: "Einen Hund oder eine Katze nach Mauritius mitnehmen",
    summary:
      "Mauritius ist tollwutfrei und wacht genau über diesen Status. Was das Einfuhrverfahren umfasst, wie lange es dauert, und warum es vor dem Genehmigungsantrag beginnen sollte.",
    body: `
<p>Mauritius ist tollwutfrei und will es bleiben, was die Mitnahme eines Tieres zu einem der langwierigsten Punkte eines Umzugs macht. Es ist durchaus machbar, und viele Familien tun es, doch der Zeitplan wird von Blutuntersuchungen und Wartefristen bestimmt und nicht von Formularen. Wer spät beginnt, erlebt womöglich, dass der Hund Monate nach der Familie ankommt.</p>
<p><strong>Wer entscheidet.</strong> Die Einfuhr lebender Tiere regelt die Livestock and Veterinary Division des Ministeriums für Agroindustrie, die für jedes Tier eine Einfuhrgenehmigung erteilt und die geltenden Richtlinien für Hunde und Katzen veröffentlicht. Zugelassen sind nur Tiere aus Ländern, die das Ministerium als tollwutfrei oder tollwutkontrolliert einstuft; ein Tier aus einem Hochrisikoland wird es nicht sein.</p>
<p><strong>Was das Tier braucht.</strong> Einen Mikrochip. Eine gültige Tollwutimpfung, verabreicht nach dem Chip und innerhalb des in den Richtlinien vorgesehenen Gültigkeitsfensters. Eine Tollwut-Antikörpertitration in einem zugelassenen Labor mit einem Ergebnis von mindestens 0,5 IE/ml, entnommen innerhalb eines festgelegten Zeitfensters vor der Reise; die Richtlinien fassen dies derzeit als nicht weniger als drei und nicht mehr als zwölf Monate vor dem Versand, und von einigen Herkunftsländern, darunter Südafrika, werden zwei Titrationen im Abstand von drei Monaten verlangt. Die üblichen Impfungen gegen Staupe, Parvovirose und die entsprechenden Katzenkrankheiten. Eine Parasitenbehandlung. In den meisten Fällen die Kastration. Eine Gesundheitsbescheinigung eines amtlichen Tierarztes im Abgangsland kurz vor dem Flug.</p>
<p><strong>Bei der Ankunft.</strong> Die Einfuhrgenehmigung muss vor der Reise des Tieres vorliegen, der Veterinärbeamte über den Flug informiert sein, und das Tier kommt in Quarantäne auf der staatlichen Station. Die Dauer hängt vom Herkunftsland und der Vorgeschichte des Tieres ab; Quellen nennen zwischen fünf Tagen und einem Monat. Planen Sie mit der längeren Angabe und freuen Sie sich, wenn es kürzer wird. Halter dürfen besuchen und sollen Futter und Liegeplatz stellen.</p>
<p><strong>Der Zeitplan.</strong> Wegen der Titration und der danach verstreichenden Frist beträgt die realistische Vorlaufzeit aus dem Stand vier bis sechs Monate, bei einem nie geimpften Tier länger. Familien, die im Frühjahr zur Erkundung kommen und im Herbst umziehen, sollten die Akte des Tieres vor dieser Reise eröffnen.</p>
<p><strong>Flüge.</strong> Direktverbindungen ab Johannesburg, Paris, London und Dubai vermeiden die Transitprobleme, an denen Tiertransporte scheitern. Hunde oberhalb der Kabinengröße reisen als Fracht im Druckraum, und die auf Tiertransporte spezialisierten Unternehmen in Südafrika und Europa übernehmen Box, Fluggesellschaft und veterinärrechtliche Bestätigung. Wir vermitteln eines davon im Rahmen des Umzugs.</p>
<p>Die obigen Anforderungen entsprechen dem Stand bei Abfassung. Das Ministerium überarbeitet sie, und wir bestätigen die geltende Richtlinie und die Einstufung des Herkunftslandes zu dem Zeitpunkt, zu dem eine Familie uns beauftragt.</p>
`,
    faqs: [
      { q: "Können wir einen Welpen oder ein Kätzchen mitnehmen?", a: "Nicht über die Impfungen der Mutter. Die erste Tollwutimpfung erfolgt mit zwölf Wochen, und das Ausfuhrverfahren läuft ab da; ein junges Tier wird also mehrere Monate alt sein, bevor es reisen kann." },
      { q: "Sind bestimmte Rassen ausgeschlossen?", a: "Mauritius beschränkt bestimmte Hunderassen. Prüfen Sie die aktuelle Liste bei der Livestock and Veterinary Division, bevor Sie davon ausgehen, dass ein bestimmter Hund mitkommen kann." },
      { q: "Wirkt sich das Tier auf unsere eigene Genehmigung aus?", a: "Nein. Die beiden Verfahren sind getrennt, sollten aber gemeinsam geplant werden, weil der Zeitplan des Tieres oft der längere ist." },
    ],
  },

  "buying-off-plan-mauritius-vefa-checklist": {
    title: "Immobilienkauf vor Fertigstellung auf Mauritius: Was Sie vor Unterzeichnung einer VEFA prüfen sollten",
    summary:
      "Die meisten Neubauten, die auf Mauritius an ausländische Käufer verkauft werden, werden verkauft, bevor sie gebaut sind. Der Schutz ist real, entscheidet sich aber bei der Unterschrift. Fünf Punkte, die zuerst zu prüfen sind.",
    body: `
<p>Der Verkauf im künftigen Fertigstellungszustand, die VEFA, ist die Form, in der die meisten Programmimmobilien auf Mauritius den Eigentümer wechseln. Der Käufer unterzeichnet vor einem Notar eine Urkunde, während das Gebäude eine Zeichnung ist, zahlt in Raten, während es wächst, und verlässt sich auf eine Bankgarantie, um es fertiggestellt zu sehen, falls der Bauträger es nicht kann. Das System funktioniert. Doch der Schutz des Käufers wird am Tag der Unterzeichnung festgelegt, und wir haben für genug Käufer in stockenden Projekten gehandelt, um zu wissen, dass der Unterschied zwischen einer durchsetzbaren und einer schwierigen Lage fast immer in der Urkunde steht.</p>
<p><strong>Wer die Fertigstellungsgarantie ausgestellt hat und was sie abdeckt.</strong> Die garantie financière d'achèvement ist das Herz einer VEFA. Verlangen Sie die Garantie selbst, nicht einen Verweis darauf. Stellen Sie die ausstellende Bank oder Versicherung fest. Lesen Sie, was sie auslöst, was sie bezahlt, und ob sie die Fertigstellung des Gebäudes abdeckt oder nur die Rückzahlung des Geleisteten. Eine Garantie von einem Institut, von dem Sie nie gehört haben, oder eine, die unter dem Vertragspreis gedeckelt ist, ist ein Warnzeichen.</p>
<p><strong>Folgt der Zahlungsplan dem Bau.</strong> Die Raten sollten an körperliche Meilensteine geknüpft sein, die ein Dritter überprüfen kann: Fundament, Rohbau, Dach, Fertigstellung, Übergabe. Ein Plan, der auf die Unterzeichnung vorgezogen ist, oder einer, der eine Zahlung bei „Beginn der Arbeiten" verlangt, ohne dies zu definieren, verschiebt das Risiko zum Käufer. Vergleichen Sie den Plan in der Urkunde mit dem im Prospekt. Sie stimmen nicht immer überein.</p>
<p><strong>Was der Bauträger zuvor fertiggestellt hat.</strong> Ein Bauträger mit drei fertiggestellten Projekten auf der Insel ist etwas anderes als einer, für den dies das erste Projekt ist, wie gut die Renderings auch sein mögen. Fragen Sie, welche Projekte er übergeben hat, wann, und ob termingerecht. Besichtigen Sie eines. Sprechen Sie dort mit einem Eigentümer. Der Notar wird das nicht für Sie tun.</p>
<p><strong>Der Übergabetermin und was bei Verzug geschieht.</strong> Die Urkunde nennt einen Übergabetermin und meist eine Liste von Ereignissen, die eine Verzögerung entschuldigen. Lesen Sie diese Liste. Entschuldigt sie beinahe alles, bedeutet der Termin wenig. Achten Sie auf eine tägliche oder monatliche Vertragsstrafe für verspätete Übergabe und prüfen Sie, ob sie gedeckelt ist. Eine Strafklausel ohne Deckel bei kurzer Entschuldigungsliste sagt Ihnen, dass der Bauträger fertig zu werden gedenkt.</p>
<p><strong>Die Struktur, über die Sie kaufen.</strong> Soll die Einheit über eine mauritische Gesellschaft und die Gesellschaft über einen Trust gehalten werden, muss diese Struktur vor der Urkunde bestehen und für die garantiegebende Bank, den Notar und das Economic Development Board annehmbar sein. Sie nach der Reservierung und vor der Urkunde einzurichten, ist Routine. Sie nach der Urkunde einzurichten, ist ein zweites Geschäft.</p>
<p>Der Notar handelt für das Geschäft, nicht für den Käufer. Seine Aufgabe ist eine gültige, ordnungsgemäß eingetragene Urkunde. Ob die Urkunde für Sie ein gutes Geschäft ist, ist nicht seine Frage. Es ist unsere, und sie stellt sich am besten vor Zahlung der Reservierungsanzahlung und nicht danach.</p>
`,
    faqs: [
      { q: "Kann ich den Zahlungsplan verhandeln?", a: "Manchmal, besonders früh in einem Projekt, wenn der Bauträger Unterschriften braucht. Häufiger steht der Plan fest, doch die Urkunde lässt sich bei Übergabebedingungen, Vertragsstrafen und dem Wortlaut der Garantie verbessern. Fragen Sie vor der Unterschrift; danach ändert sich nichts." },
      { q: "Was, wenn der Bauträger den Bau einstellt?", a: "Die Fertigstellungsgarantie wird gezogen, und der Garantiegeber finanziert je nach ihren Bedingungen entweder die Fertigstellung oder erstattet den Käufern. Das Verfahren läuft über den Notar und den Garantiegeber und kann dauern. Käufer, die die Bedingungen der Garantie vor der Unterschrift kennen, stehen weit besser da als jene, die sie erst beim Baustopp zum ersten Mal lesen." },
      { q: "Hängt die Aufenthaltsgenehmigung von der Fertigstellung ab?", a: "Die Genehmigung wird beantragt, sobald die Urkunde unterzeichnet und der Erwerb beim EDB erfasst ist; sie wartet also nicht auf das Gebäude. Scheitert das Projekt und wird der Kauf rückabgewickelt, entfällt die Genehmigung mit ihm." },
    ],
  },

  "retiring-to-mauritius-from-germany-austria-switzerland": {
    title: "Ruhestand auf Mauritius aus Deutschland, Österreich oder der Schweiz: die Genehmigung und die steuerlichen Fragen",
    summary:
      "Die Genehmigung für Ruheständler ist unkompliziert. Das Zusammenspiel von mauritischer Ansässigkeit und einer deutschen, österreichischen oder schweizerischen Rente ist es nicht. Was vor dem Umzug zu klären ist.",
    body: `
<p>Jeden Monat meldet sich ein Paar aus München, Wien oder Zürich, das Mauritius im Winterurlaub entdeckt hat und wissen möchte, wie schwer es wäre zu bleiben. Die Genehmigung ist der einfache Teil. Die steuerliche Lage ist der Punkt, an dem die Entscheidung tatsächlich fällt, und der Teil, den die meisten Webseiten entweder auslassen oder falsch darstellen.</p>
<p><strong>Die Genehmigung.</strong> Wer 50 Jahre oder älter ist, kann eine Aufenthaltsgenehmigung für Retired Non-Citizens beantragen. Sie läuft zehn Jahre, verlangt keinen Immobilienerwerb und beruht darauf, jährlich 24.000 USD aus dem Ausland auf ein mauritisches Bankkonto zu überweisen, also 2.000 USD im Monat. Ein Ehepartner unter 50 kommt als Familienangehöriger hinzu. Eine Beschäftigung ist mit dieser Genehmigung nicht erlaubt, eine Beteiligung als Gesellschafter dagegen schon. Nach fünf Jahren und Überweisungen von insgesamt 200.000 USD kann der Inhaber ein zwanzigjähriges Permanent Residence Permit beantragen. Das ist der gesamte Rahmen.</p>
<p><strong>Steuerliche Ansässigkeit.</strong> Wer 183 Tage oder mehr in einem Steuerjahr auf Mauritius verbringt, ist hier steuerlich ansässig. Mauritius besteuert ausländische Einkünfte nach der Remittance-Basis und hat Doppelbesteuerungsabkommen mit Deutschland und weiteren europäischen Staaten in Kraft. Ob ein solches mit Ihrem Land besteht und was es zu Renten sagt, ist als Erstes zu klären.</p>
<p><strong>Die Fragen an einen Steuerberater, bevor Sie entscheiden.</strong> Wir sind keine Steuerberater und geben keine steuerlichen Gutachten ab. Wir wissen aber, welche Fragen eine brauchbare Antwort erzeugen.</p>
<ul>
<li>Welche meiner Einkunftsquellen werden nach dem Abkommen im Entstehungsland besteuert und welche folgen mir nach Mauritius? Gesetzliche Renten, Betriebsrenten, private Leibrenten und Kapitaleinkünfte werden oft unterschiedlich behandelt.</li>
<li>Was verlangt mein Heimatland, um anzuerkennen, dass ich fortgezogen bin? Abmeldung, Ende eines gewöhnlichen Aufenthalts, Zahl der Tage, die ich dort noch verbringen darf. Deutschland und Österreich sehen insbesondere auf Bindungen, nicht nur auf Tage.</li>
<li>Wenn ich eine Wohnung in der Heimat behalte, hält mich das dort steuerlich ansässig?</li>
<li>Wie wirkt die mauritische Remittance-Basis mit den von der Genehmigung verlangten Überweisungen zusammen? Geld, das zur Erfüllung der Bedingung hereingebracht wird, ist definitionsgemäß remittiert.</li>
<li>Gibt es eine Wegzugsbesteuerung, eine gestundete Belastung oder eine Rückforderung bei einem Renten- oder Anlageprodukt, das ich halte, wenn ich nicht mehr ansässig bin?</li>
<li>Wird meine Krankenversicherung mich weiterhin im Ausland abdecken, und was kostet mauritischer Privatschutz in meinem Alter?</li>
</ul>
<p>Die Antworten unterscheiden sich zwischen den drei Ländern und zwischen Personen so stark, dass keine Webseite sie geben kann. Was ein guter Berater von Ihnen braucht, ist eine klare Aufstellung Ihrer Einkunftsquellen, der Vermögenswerte, die Sie in der Heimat behielten, und der Tage, die Sie wo zu verbringen gedenken. Was wir tun: den Berater vermitteln, ihm diese Angaben vorlegen und den Genehmigungsantrag zurückhalten, bis die Antworten vorliegen.</p>
<p>Die meisten Paare, die diese Fragen stellen, ziehen dennoch um. Sie ziehen mit einem Plan statt mit einer Annahme um, und das ist der einzige Unterschied, auf den es ankommt.</p>
`,
    faqs: [
      { q: "Muss ich mein Zuhause in Europa verkaufen?", a: "Für die Genehmigung nicht. Ob das Behalten Ihre steuerliche Ansässigkeit in der Heimat berührt, ist eine Frage für Ihren dortigen Berater, und die Antwort unterscheidet sich zwischen Deutschland, Österreich und der Schweiz." },
      { q: "Kann ich Auto, Möbel und persönliche Gegenstände mitbringen?", a: "Ja, und ein Inhaber einer Aufenthaltsgenehmigung darf Umzugsgut unter Bedingungen zollbegünstigt einführen. Ein Fahrzeug ist eine eigene Frage und lohnt sich oft nicht. Wir behandeln dies im Rahmen des Umzugs." },
      { q: "Kann ich mit 65 und ohne mauritisches Einkommen ein Bankkonto eröffnen?", a: "Ja. Die Banken kennen die Genehmigung für Ruheständler. Genau prüfen werden sie die Herkunft Ihres Vermögens; die Akte, die wir für die Bank vorbereiten, ist daher ausführlicher als die für die Genehmigung." },
    ],
  },

  "south-africans-relocating-to-mauritius-permit-and-cost": {
    title: "Südafrikaner, die nach Mauritius ziehen: welche Genehmigung, und was das erste Jahr kostet",
    summary:
      "Die drei Aufenthaltsmöglichkeiten, die südafrikanische Familien am häufigsten wählen, und eine ehrliche Aufstellung, wohin das Geld in den ersten zwölf Monaten geht.",
    body: `
<p>Südafrikaner sind die größte Gruppe unter den ausländischen Zuzüglern auf Mauritius, und die Gründe sind bekannt: vier Stunden Flug, dieselbe Zeitzone, englischsprachige Schulen, eine stabile Währung und ein funktionierender Staat. Die Frage, die uns am häufigsten gestellt wird, lautet nicht, ob man kommen soll, sondern mit welcher Aufenthaltsmöglichkeit und zu welchem Preis. Hier die kurze Fassung.</p>
<p><strong>Drei Aufenthaltsmöglichkeiten.</strong> Wer hier ein Unternehmen führen wird, nimmt das Occupation Permit der Kategorie Investor: 100.000 USD in eine mauritische Gesellschaft, Umsatzbedingungen ab dem dritten Jahr, zehn Jahre Gültigkeit. Eine Fachkraft oder ein Berater, der allein arbeitet, nimmt das Self-Employed Permit mit 50.000 USD. Wer über 50 ist und von südafrikanischen Einkünften lebt, nimmt die Genehmigung für Ruheständler auf Überweisungen von 24.000 USD im Jahr. Eine vierte Aufenthaltsmöglichkeit, der Kauf eines Zuhauses in einem zugelassenen Programm ab 375.000 USD, begründet einen Anspruch auf eine Aufenthaltsgenehmigung, solange die Immobilie gehalten wird, und passt zu Familien, die ohnehin kaufen wollten. Die meisten südafrikanischen Familien nutzen eine der ersten drei Aufenthaltsmöglichkeiten und mieten im ersten Jahr.</p>
<p><strong>Wohin das Geld im ersten Jahr geht.</strong> Sieht man von der Investition der Genehmigung selbst ab, die Betriebskapital oder Lebensgeld ist und kein Honorar, verteilen sich die Kosten auf sechs Gruppen, grob in absteigender Reihenfolge.</p>
<ul>
<li>Wohnen. Die Miete für ein Haus mit drei Schlafzimmern und Pool im Norden oder Westen ist der größte Posten. Kautionen, Maklerhonorare und die ersten Monatsmieten werden vor der Ankunft gezahlt.</li>
<li>Schule. Die internationalen Schulen rechnen in Rupien ab, und die Gebühren sind erheblich, liegen aber deutlich unter dem Äquivalent am Golf oder in Singapur. Plätze füllen sich früh, und Anmeldegebühren werden bei Zusage fällig.</li>
<li>Gründung. Eintragung, eingetragener Sitz und Company Secretary, bei Bedarf ein ansässiger Direktor sowie das Bankkonto. Für den Investorweg ist dies ein festes Paket; für den Ruhestandsweg ist es minimal.</li>
<li>Die Genehmigung selbst. Die staatlichen Gebühren sind moderat. Unser Honorar für die Vorbereitung und Führung des Antrags steht vor jedem Beginn im schriftlichen Angebot.</li>
<li>Krankenversicherung. Ein privater Schutz, der auf Mauritius gilt und die Überweisung nach Südafrika abdeckt, ist nicht optional und sollte vor der Ankunft eingerichtet werden.</li>
<li>Fahrzeug und Haushalt. Ein Auto, Zulassung und Versicherung; Versorgung und Anschlüsse; auf Wunsch Hauspersonal, zu nach südafrikanischen Maßstäben niedrigen Löhnen.</li>
</ul>
<p><strong>Devisenkontrolle.</strong> Kapital aus Südafrika zu verlagern unterliegt den Regeln der South African Reserve Bank und Ihren jährlichen Freibeträgen, und der Zeitpunkt der Überweisungen sollte mit Blick auf die Frist der Genehmigung geplant werden. Das Investor- und das Self-Employed-Permit verlangen, dass die Anfangsinvestition binnen 60 Tagen nach Erteilung eintrifft; eine verzögerte Überweisung lässt die Genehmigung entfallen. Wir beraten nicht zur südafrikanischen Devisenkontrolle, aber wir takten die Genehmigung so, dass das Geld bereitsteht, wenn die Frist zu laufen beginnt.</p>
<p><strong>Was wir einem Freund sagen würden.</strong> Mieten Sie, bevor Sie kaufen. Wählen Sie die Schule vor dem Haus. Lassen Sie das Bankkonto eröffnen, bevor die Genehmigung erteilt wird, nicht danach. Planen Sie zwei Reisen vor dem Umzug ein, eine zum Sehen und eine zum Unterschreiben. Und entscheiden Sie sich danach, wie das Unternehmen oder der Haushalt in drei Jahren aussehen wird, nicht nach der kleinsten Zahl auf der Seite.</p>
`,
    faqs: [
      { q: "Kann ich mein südafrikanisches Unternehmen behalten und von Mauritius aus führen?", a: "Ja, und viele tun das, über eine mauritische Gesellschaft, die mit der südafrikanischen kontrahiert oder das Exportgeschäft übernimmt. Die Struktur ist für beide Steuersysteme bedeutsam und sollte vor dem Genehmigungsantrag entworfen werden, nicht danach." },
      { q: "Darf mein Ehepartner arbeiten?", a: "Nicht mit einer Genehmigung als Familienangehöriger. Die übliche Gestaltung ist ein Investor Permit für den einen und ein Professional Permit für den anderen Ehepartner, angestellt bei derselben mauritischen Gesellschaft, oder ein zweites Occupation Permit im eigenen Recht." },
      { q: "Wie lange dauert es, bis wir umziehen können?", a: "Vom ersten Gespräch bis zur Familie im Haus mit Kindern in der Schule sind drei bis sechs Monate realistisch, wobei meist das Bankkonto und der Schulplatz das Tempo vorgeben und nicht die Genehmigung." },
    ],
  },

  "occupation-permit-changes-2026-27-budget": {
    title: "Was das Budget 2026-27 bei den Occupation Permits geändert hat",
    summary:
      "Höhere Schwellen für Investoren, eine einheitliche Kategorie für Angestellte und strengere Einkommensbedingungen für Selbstständige. Was das bedeutet, wenn Sie in diesem Jahr umziehen wollen.",
    body: `
<p>Das Budget 2026-27 brachte die bedeutendste Überarbeitung des Rahmens für Occupation Permits seit mehreren Jahren, und das Economic Development Board hat inzwischen überarbeitete Richtlinien erlassen, um sie umzusetzen. Vier Änderungen sind für jeden bedeutsam, der einen Umzug plant.</p>
<p><strong>Die Investorenschwelle hat sich verdoppelt.</strong> Die Mindestanfangsinvestition beträgt nun 100.000 USD, aus dem Ausland auf das mauritische Konto der Gesellschaft überwiesen, binnen 60 Tagen nach Erteilung der Genehmigung. Auch die anschließenden Umsatzbedingungen sind neu: 5 Millionen MUR im Jahr ab dem dritten Jahr der Registrierung, steigend auf 8 Millionen MUR ab dem fünften Jahr für die Verlängerung. Ein Investor, dessen Geschäftsplan diese Zahlen realistischerweise nicht erreichen kann, sollte genau prüfen, ob der Investorweg der richtige ist.</p>
<p><strong>Eine Kategorie für Angestellte.</strong> Die früheren Stufen ProPass und Expert Pass wurden zusammengeführt. Das monatliche Mindestgrundgehalt beträgt nun in allen Branchen 50.000 MUR. Angestellte, die eine Genehmigung noch nach dem alten Kriterium von 30.000 MUR halten, bleiben auf dieser Grundlage für eine Verlängerung berechtigt, was bestehenden Inhabern Zeit verschafft.</p>
<p><strong>Einkommensbedingungen für Selbstständige.</strong> Die Anfangsinvestition bleibt bei 50.000 USD, die Einkommensbedingungen sind nun aber ausdrücklich geregelt: 2 Millionen MUR im Jahr ab dem dritten Jahr und 3 Millionen MUR ab dem fünften Jahr für die Verlängerung. Beim Antrag sind drei Absichtserklärungen erforderlich, zwei davon von lokalen Kunden.</p>
<p><strong>Das Family Occupation Permit ist entfallen.</strong> Die Kategorie wurde abgeschafft. Familien laufen nun über den Hauptinhaber und Genehmigungen für Familienangehörige, was für die meisten ohnehin die bisherige Praxis war.</p>
<p>Nichts davon macht Mauritius für diejenigen schwerer erreichbar, die es gewinnen möchte. Es macht die Wahl folgenreicher. Der Unterschied zwischen Investor und Self-Employed, oder zwischen einem Occupation Permit und dem Aufenthalt über eine Immobilie, bemisst sich nun in echtem Geld und echten Umsatzpflichten und verdient eine Stunde Nachdenken, bevor irgendetwas eingereicht wird.</p>
`,
  },

  "investor-or-self-employed": {
    title: "Investor oder Self-Employed: das richtige Occupation Permit wählen",
    summary:
      "Die beiden Aufenthaltsmöglichkeiten für Menschen, die auf Mauritius auf eigene Rechnung arbeiten, unterscheiden sich in Kapital, Struktur und Pflichten. Ein kurzer Leitfaden, welcher passt.",
    body: `
<p>Die meisten, die auf Mauritius auf eigene Rechnung ihren Lebensunterhalt verdienen werden, kommen mit einer von zwei Genehmigungen im Sinn. Die Wahl zwischen ihnen hängt weniger von der Tätigkeit ab als von ihrer Gestalt.</p>
<p><strong>Kapital.</strong> Das Self-Employed Permit verlangt 50.000 USD, aus dem Ausland überwiesen. Das Investor Permit verlangt 100.000 USD, auf das Konto einer Gesellschaft. Für viele entscheidet dieser Unterschied die Sache, und daran ist nichts falsch.</p>
<p><strong>Struktur.</strong> Ein Self-Employed-Inhaber arbeitet im eigenen Namen oder über eine Ein-Personen-Gesellschaft, darf eine örtliche Verwaltungskraft beschäftigen und keine weiteren Fachkräfte anstellen. Ein Investor besitzt und leitet eine mauritische Gesellschaft, die einstellen, kontrahieren und wachsen kann. Ist eine Tätigkeit als Einzelperson geplant, ist Self-Employed einfacher und günstiger zu unterhalten. Ist eine Gesellschaft mit Angestellten und eigenem Namen geplant, ist der Investorweg das nötige Fundament.</p>
<p><strong>Branche.</strong> Self-Employed ist auf Dienstleistungen beschränkt. Handel, Fertigung, Gastgewerbe und Projektentwicklung sind definitionsgemäß Investorentätigkeiten.</p>
<p><strong>Pflichten.</strong> Beide tragen Einkommens- oder Umsatzbedingungen ab dem dritten Jahr und höhere ab dem fünften Jahr für die Verlängerung: 2 und 3 Millionen MUR für Selbstständige, 5 und 8 Millionen MUR für Investoren. Die Zahlen des Investors sind höher, weil von einer Gesellschaft mehr erwartet wird, doch die Zahlen des Selbstständigen sind persönliches Einkommen und nicht immer leichter zu erreichen.</p>
<p><strong>Die Familie.</strong> Beide Genehmigungen erstrecken sich auf Ehepartner, Kinder und Eltern als Familienangehörige. Sind beide Partner im Unternehmen tätig, ist die übliche Gestaltung ein Investor Permit für den einen und ein Professional Permit für den anderen, angestellt bei derselben Gesellschaft.</p>
<p>Die falsche Wahl ist selten fatal, da ein Inhaber später die Kategorie wechseln kann, sie kostet aber Zeit und einen zweiten Antrag. Die richtige Wahl ist meist nach einem Gespräch darüber klar, wie das Unternehmen im dritten Jahr aussehen wird.</p>
`,
  },

  "golden-visa-what-it-adds": {
    title: "Golden Visa: Wie es die bestehenden Aufenthaltsmöglichkeiten ergänzt",
    summary:
      "Mauritius hat ein Golden Visa über 1 Million USD angekündigt, das Inhabern nach erfolgter Investition den Antrag auf einen zwanzigjährigen Daueraufenthalt ermöglicht. Wo es neben den bereits bestehenden Genehmigungen steht und für wen es gedacht ist.",
    body: `
<p>Mauritius hat im April 2026 ein Golden Visa gebilligt und es über die Budgetmaßnahmen gesetzlich verankert. Die Antragsrichtlinien und der Starttermin stehen vom Economic Development Board noch aus; das Folgende ist daher der angekündigte Rahmen, nicht das bereits praktizierte Verfahren.</p>
<p><strong>Die Ausgestaltung.</strong> Ein Visum zur mehrfachen Einreise für eine vermögende Person und die engste Familie, gültig bis zu zwei Jahre und verlängerbar. Beim Antrag verpflichtet sich der Inhaber schriftlich, binnen zwölf Monaten 1 Million USD auf Mauritius zu investieren. Nach Abschluss der Investition kann er ein zwanzigjähriges Permanent Residence Permit beantragen. Die Erfüllung der Voraussetzungen führt nicht automatisch zur Erteilung, und die Umwandlung erfolgt nicht von selbst. Die Regierung hat von rund 100 Begünstigten im Jahr und einem Bearbeitungsziel von fünf Werktagen gesprochen.</p>
<p><strong>Was zählt.</strong> Jede unternehmerische Tätigkeit außer dem Kauf von Wohnimmobilien in den Immobilienprogrammen des EDB. Fintech, künstliche Intelligenz, Biotechnologie, erneuerbare Energien und internationales Treasury wurden als Zielbranchen genannt. Ein Zuhause in den Programmen darf weiterhin gekauft werden, liegt aber außerhalb der 1 Million USD.</p>
<p><strong>Wo es steht.</strong> Mauritius bietet bereits den Aufenthalt über eine Immobilie ab 375.000 USD, ein Investor Permit ab 100.000 USD mit Umsatzpflichten und eine Genehmigung für Ruheständler auf Überweisungen von 24.000 USD im Jahr. Das Golden Visa verlangt mehr Kapital als alle diese Aufenthaltsmöglichkeiten. Dafür können Inhaber nach dem ersten Jahr einen Daueraufenthalt beantragen und frei entscheiden, wie sie das Kapital einsetzen. Es verleiht kein Recht zu arbeiten; erwartet wird eine Investition, keine Beschäftigung.</p>
<p><strong>Für wen es gedacht ist.</strong> Für eine Familie mit einzusetzendem Kapital, die rasch auf Mauritius sein und eine langlaufende Genehmigung halten möchte, die weder an die tägliche Führung eines Unternehmens noch an den Besitz einer bestimmten Immobilie gebunden ist. Für einen Gründer, der hier eine Gesellschaft führen wird, bleibt das Investor Permit die bessere Wahl. Für eine Person über 50, die von Einkünften aus dem Ausland lebt, bleibt die Genehmigung für Ruheständler die einfachste.</p>
<p>Anträge durchlaufen eine behördenübergreifende Prüfung unter Beteiligung der Financial Crimes Commission, der Financial Intelligence Unit, der Financial Services Commission und der Bank of Mauritius. Die Herkunft des Vermögens wird gründlich geprüft. Die Dokumentationsanforderungen veröffentlichen wir, sobald die Richtlinien des EDB vorliegen.</p>
`,
  },
};
